# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt: # SignalK MQTT HA Bridge
  # https://developers.home-assistant.io/docs/core/entity/sensor/
  sensor:
    - name: "Wind App Speed"
      unique_id: "speedApparent"
      #device_class: "wind_speed"
      state_topic: "vessels/self/environment/wind/speedApparent"
      unit_of_measurement: "kn"
      value_template: "{{ (value_json * 1.9438452) | round(1) }}"

    - name: "Wind App Angle"
      unique_id: "angleApparent"
      state_topic: "vessels/self/environment/wind/angleApparent"
      unit_of_measurement: "deg"
      value_template: "{{ (value_json * 180 / 3.14159265359) | round(1) }}"

lovelace:
  mode: yaml
