@startuml
start
:Download OpenPlotter NOOB;
:Create SD Card with NOOB;
:Boot Pi from SD card;
:Install OpenPlotter;
:Install Raspbian Updates and Firmware Updates;
:Configure Pi, Kernel, Interfaces, Video Memory Split;
:Configure Touchscreen, Onscreen Keyboard, twofing, svkbd, desktop;
:Update OpenPlotter applications;
:Configure Serial, I2C, PyPilot, IMU, GPS sensor, AIS;
:Configure SignalK Connections, SignalK Time Sync, SignalK NMEA;
split
 :Download Charts for OpenCPN;
split again
 :Install Plugins for OpenCPN;
split again
 :Create OpenCPN to SignalK Connection;
end split
:Configure OpenCPN, UI, Dashboard, Plugins;
split
:Configure Network;
split again
:Configure SDR-RTL;
end split
split
:Calibrate IMU;
split again
:Configure Weather Services;
end split
:Test;
partition On-the-Boat {
	:Mount the hardware in the cabin and the cockpit;
	:Attach Antennas;
	:Set up WiFi router connection to the marina;
	:Calibrate Leveling and Axis;
	:Attach Wind, Speed, Depth Sensors;
	:Attach AutoPilot;
	:Test;
}

stop
@enduml
