@startuml

skinparam BackgroundColor transparent
skinparam componentStyle rectangle
skinparam defaultTextAlignment center

left to right direction

card "Chartplotting" {
  component "Charts: "
  component "Weather: GRIB, WeatherFax, Satellite, Climatology"
  component "Routes: Tracking, Weather Routing, MOB Marking, Waypoints"
  component "Sailing Performance: Polars, Laylines"
  component "Tides, Currents"
  component "AIS, Radar"
  component "Alarms: Anchor, Deadman, Collision Course, Landfall, Depth, Off-Course, Autopilot, Gybing"
}

card "Internet" {
  component "On-line Charts, Tiling Servers"
  component "On-line Weather (Winds, Waves, Lightnings, Warnings, Forecasts, etc)"
  component "Location Reporting, Track Recording"
  component "Browser"
  component "Email"
  component "Messaging"
  component "Social Networks"
  component "Remote Desktop"
}

card "Multimedia" {
  component "Audio: Spotify, Local, Radio"
  component "Video: VLC, Movies via Chromium"
}

card "Marine Data Server" as MDS {
  component "Dashboards"
  component "Alerts"
}

card "Interfaces" {
  component "NMEA 0183"
  component "NMEA 2000"
  component "ModBus"
  component "i2c"
  component "gpsd"
  component "SignalK"
  component "mqtt"
}

card "Radio" {
  component "SSB"
  component "SDR"
  component "LoRa"
}

Chartplotting -l-- Interfaces
Chartplotting -u-- Internet

MDS -u-- Internet
MDS -l-- Chartplotting
MDS -l-- Radio

Internet -d- Multimedia


@enduml
