@startuml
actor Helmsman [
 Helmsman
]
node OpenCPN [
 OpenCPN
]
node AvNav [
 AvNav
]
node PyPilot_Web [
 PyPilot_Web
]
node KIP_Dashboard [
 KIP_Dashboard
]
rectangle gpsd [
 gpsd
 ----
 TCP, UDP
]
rectangle SignalK [
 SignalK
 ----
 HTTP, TCP, UDP, WebSockets
]
rectangle PyPilot [
 PyPilot
]
node GPS_SerialDevices [
 GPS_SerialDevices
 ----
 /dev/ttyLYS_gps_*, etc
]
node CanBus_Devices [
 CAN_Devices NMEA 2000
 ----
 ifconfig can0 interface
]
node SerialDevices [
 SerialDevices NMEA 0183
 AIS, Wind, Speed, Depth, etc
 ----
 /dev/ttyLYS*, etc
]
node OtherSensors [
 Other Sensors (Barometer, Temp, Humidity, etc)
 ----
 I2C, 1W, etc
]
node IMU [
 IMU Sensors (Compass, Gyro, Accelerometer)
 ----
 I2C
]
node Servo [
 Servo, Actuator Controller
 ----
 Servo
]

GPS_SerialDevices --> gpsd
GPS_SerialDevices --> SignalK
SerialDevices --> SignalK
CanBus_Devices --> SignalK
OtherSensors --> SignalK
IMU --> PyPilot
Servo <-- PyPilot
gpsd --> SignalK
gpsd --> OpenCPN
PyPilot --> OpenCPN
PyPilot --> AvNav
PyPilot --> SignalK
SignalK --> OpenCPN
SignalK --> PyPilot
SignalK --> AvNav
SignalK --> KIP_Dashboard

PyPilot <-- PyPilot_Web
PyPilot --> PyPilot_Web

Helmsman -- PyPilot_Web
Helmsman -- OpenCPN
Helmsman -- AvNav
Helmsman -- KIP_Dashboard

@enduml
