@startuml

actor Skipper [
 Skipper
]

node RPI [
 <b>Rpi4, BBN OS
 ----
 Local WiFi
 CanBus Interface
 Sound Card
 SSD
]

rectangle GPS [
 GPS USB
]

rectangle IMU [
 IMU
 ----
 compass, gyro, accel
]

rectangle NMEA_2000 [
 <b>NMEA2000 Bus
 ----
 engine sensors,
 fishfinder, sonar,
 etc
]

node NMEA_Mux [
 NMEA Multiplexer
 ----
 bidirectional Seatalk1
]

rectangle NMEA_0183 [
 <b>NMEA 0183 Devices
 ----
 AIS transducer/receiver
 GPS, VHF, compass
 Wind, Depth, Speed
]

rectangle AP [
 Autopilot
]

node Eth_Hub [
 Ethernet Hub
]

node USB_Hub [
 USB Hub
]

node Router [
 LTE/WiFi Router
]

rectangle Dish_Router [
 StarLink Router,
 Dish
]

node Radar [
 Radar
]

node Touchscreen [
 <b>HDMI Touchscreen
]

rectangle Speakers [
 Speakers
]

rectangle Cameras [
 Cameras
]

node SDR [
 SDR Radio
]

node SSB [
 SSB Radio
]

cloud WiFi_Local [
 Local WiFi
]

rectangle Iridium [
 Iridium Phone
]

rectangle Other_Sensors [
 Other_Sensors
 ----
 IoT, 1w, i2c, etc
 battery/chargers monitoring
 fluid levels
 env temp/pressure/humid
]

node AC [
 A/C
]

node Fridge [
 Fridge
]

rectangle Lights [
 Lights
]

rectangle Keyboard_Mouse [
 Keyboard
 Mouse
]

rectangle Weather [
 NavTex
 WeatherFax
 Barograph
]

rectangle SmartPhone [
 SmartPhones
 Tablets
]

database NAS [
 NAS
 ----
 Audio/Video Lib
 Charts, Backups, Tracks,
 Time Series Data, etc
]

cloud Cloud_Internet [
 <b>Internet
 Cloud Storage
 Cloud Services
]

RPI -- GPS
RPI -l- IMU
RPI -- NMEA_2000
RPI -- NMEA_Mux
RPI -u- Eth_Hub
RPI -- USB_Hub
RPI -u- Touchscreen
RPI -u- Cameras
RPI -u-> Speakers
RPI -- SSB
RPI -u- Iridium
RPI -- Other_Sensors
RPI -u- WiFi_Local
RPI -u- Keyboard_Mouse

SmartPhone -- WiFi_Local

Eth_Hub -r- Router
Eth_Hub -- Radar
Eth_Hub -- NAS
Eth_Hub -u- Dish_Router

USB_Hub -- SDR
USB_Hub -- Weather

Other_Sensors -- AC
Other_Sensors -- Fridge
Other_Sensors -- Lights

NMEA_Mux -- NMEA_0183
NMEA_Mux -- AP

Cloud_Internet -- Dish_Router
Cloud_Internet -- Router
Cloud_Internet -- Iridium

Skipper -- Touchscreen
Skipper -- Speakers
Skipper -- Cameras
Skipper -- Iridium
Skipper -- SmartPhone
Skipper -- Keyboard_Mouse

@enduml
