@startuml

actor Skipper [
 Skipper
]

node Panel [
 <b>Nav Station Panel
 ----
 Switches
 Fuses
 USB Data Ports
 HDMI Ports
 Audio Ports (In/Out)
 SIM Card Port: [[https://www.data-alliance.net/cable-gland-for-fiber-usb-sim-terminal-block-waterproof-ip67-feed-thru/ Buy Here]]
 SD Card Port (?)
 Status Lights
 Volt/Amm Meters
 12v Socket
]

node Batteries #moccasin [
 <b>Batteries
]

node Chargers #moccasin [
 Chargers
]

node Engines #moccasin [
 <b>Engines
]

node Antenna_VHF #moccasin [
  VHF Antenna
]

node AIS [
  AIS
]

node Antenna_AIS [
  AIS Antenna
]

node Solar_Pan #moccasin [
  Solar Panels
]

node Wind_Gen #moccasin [
  Wind Generator
]

node RPI #palegreen [
 <b>Rpi4, BBN OS
 ----
 Local WiFi
 CanBus Interface
 Sound Card
 SSD
]

rectangle GPS [
 GPS USB
]

rectangle IMU [
 IMU
 ----
 compass, gyro, accel
]

cloud NMEA_2000 #moccasin [
 <b>NMEA2000 Bus
 ----
 engine sensors,
 fishfinder, sonar,
 etc
]

node NMEA_Mux [
 NMEA Multiplexer
 ----
 bidirectional Seatalk1
]

node NMEA_Eth_Mux [
 NMEA Ethernet Multiplexer
]

cloud NMEA_0183 #moccasin [
 <b>NMEA 0183 Devices
 ----
 AIS transducer/receiver
 GPS, VHF, compass
 Wind, Depth, Speed
]

rectangle AP #moccasin [
 Autopilot
]

node Eth_Hub [
 Ethernet Switch
]

node USB_Hub [
 USB Hub
]

node Router [
 LTE/WiFi Router
]

rectangle Dish_Router [
 StarLink Router,
 Dish
]

node Radar #moccasin [
 Radar
]

node Touchscreen [
 <b>HDMI Touchscreen
]

rectangle Speakers [
 Speakers
]

rectangle Mic [
 Microphone
]

rectangle Cameras [
 Cameras
 ----
 WebCam, Mast,
 Night (FLIR),
 low light vision,
 IP, docking, etc
]

node SDR [
 SDR Radio
]

node SSB #moccasin [
 SSB/HAM Radio
]

cloud WiFi_Local [
 Local WiFi
]

cloud Bluetooth [
 Bluetooth
]

rectangle Iridium #moccasin [
 Iridium Phone
]

rectangle Other_Sensors [
 Other_Sensors
 ----
 IoT, 1w, i2c, etc
 batteries monitoring
 chargers (wind, solar, diesel gen)
 fluid levels
 env temp/pressure/humid
 dangerous gases sensors
 lightning strike sensors
]

rectangle Remote_Desktop [
 Remote Desktop (VNC)
]

node VHF #moccasin [
 VHF
]

node AC #moccasin [
 A/C
 Heater
]

node Pumps #moccasin [
 Pumps
 ----
 Bilge
 Fresh Water
 Black Water
]

node Fridge #moccasin [
 Fridge
 Watermaker
 Live well
]

rectangle Lights_Fans #moccasin [
 Lights: (Nav, Anchor,
 Running, Mast, Cabin,
 Underwater, Search, etc)
 Fans
 Bilge/Engine Blower
]

rectangle Keyboard_Mouse [
 Keyboard
 Mouse
]

rectangle Weather [
 NavTex
 WeatherFax
 Barograph
]

rectangle SiriusXM #moccasin [
 SiriusXM Marine
]

rectangle SmartPhone [
 SmartPhones
 Tablets
]

database NAS [
 NAS
 ----
 Audio/Video Lib
 Charts, Backups, Tracks,
 Docs, Logs,
 Crew Docs, Float Plans,
 Inventory, Provisioning,
 Time Series Data, etc
]

node Winches #moccasin [
 Anchor Windlass
 Power Winches
 Bow Thruster
]

cloud Cloud_Internet [
 <b>Internet
 ----
 Cloud Storage: Rclone supported
 Cloud Services: Marina Booking, Marine Traffic
 Location Reporting: saillogger.com
 Social: FB, FindACrew, BoatSetter
 Messengers: FB, WA
 WWW browser: Chromium
 Music: Spotify
 Movies: via Browser
 Weather: Grib, Windy, WeatherFax, NOAA,
    Lightnings Map
 Charts: MbTiles, NOAA, Navionics, etc
 Email: any
 Remote Desktop Access: Cloud VNC
 Software updates: apt, SignalK, OpenCPN, AvNav, etc
 WebCam
]

cloud Lora [
 LoraWAN
 Asset Tracking
 Dinghy Locator
]

rectangle Esp32 [
 m5stack, seeeduino
 arduino/ESP32
]

rectangle Radio_Data [
 WeatherFax
 NOAA Weather
 Inmarsat
 AIS
 NavTex
 WinLink email, etc
]

node AP_2 [
 TinyPilot
 ---
 Software: PyPilot
 Hardware: TinyPilot
 [[https://pypilot.org/store Buy Here]]
]

node Rudder #moccasin [
 <b>Rudder
 ----
 Rudder Drive Motor
]

RPI -- NMEA_2000
RPI -- NMEA_Mux
RPI -u- Eth_Hub
RPI -- USB_Hub
RPI -u- Touchscreen
RPI -u- Cameras
RPI -u- Speakers
RPI -u- Mic
RPI -u- Iridium
RPI -- Other_Sensors
RPI -d- Esp32
RPI -u- WiFi_Local
RPI -u- Keyboard_Mouse
RPI -l- Panel

Radio_Data -u- RPI
Radio_Data -u- SSB

Bluetooth -u- Speakers
Bluetooth -u- Keyboard_Mouse
Bluetooth -u- Mic
Bluetooth -u- SmartPhone
Bluetooth -r- RPI

Panel -- Touchscreen
Panel -- USB_Hub
Panel -- Batteries

SmartPhone -- WiFi_Local
AP_2 -u- WiFi_Local

NMEA_2000 -- SiriusXM
NMEA_2000 -- NMEA_Mux
NMEA_2000 -- NMEA_Eth_Mux

VHF -u- NMEA_Mux
AIS -u- NMEA_Mux

Eth_Hub -r- Router
Eth_Hub -- Radar
Eth_Hub -- NAS
Eth_Hub -- NMEA_Eth_Mux
Eth_Hub -u- Dish_Router

USB_Hub -- SDR
USB_Hub -- Weather
USB_Hub -r- GPS

Other_Sensors -r- AC
Other_Sensors -- Fridge
Other_Sensors -- Lights_Fans
Other_Sensors -- Pumps

NMEA_Mux -l- NMEA_0183
NMEA_Eth_Mux -- NMEA_0183
NMEA_Mux -- AP

AP -- Rudder
AP_2 -- Rudder
AP_2 -- IMU

Esp32 -- Lora
Esp32 -- Winches

Cloud_Internet -- Dish_Router
Cloud_Internet -- Router
Cloud_Internet -- Iridium
Cloud_Internet -- Remote_Desktop

Skipper -- Touchscreen
Skipper -- Speakers
Skipper -- Mic
Skipper -- Cameras
Skipper -- Iridium
Skipper -- SSB
Skipper -- SmartPhone
Skipper -- Keyboard_Mouse
Skipper -- Remote_Desktop
Skipper -- Panel

Chargers -- Solar_Pan
Chargers -- Batteries
Chargers -- Wind_Gen
Engines -- Batteries

VHF -- Antenna_VHF
AIS -- Antenna_AIS

Other_Sensors -- Engines
Other_Sensors -- Batteries

@enduml
