= Bareboat Necessities OS Documentation
mgrouch <mgrouch@users.noreply.github.com>
{docdate}, Bareboat Necessities OS Documentation
:imagesdir: images
:doctype: book
:organization: Bareboat Necessities
:title-logo-image: image:bareboat-necessities-logo.svg[Bareboat Necessities Logo]
ifdef::backend-pdf[]
:source-highlighter: rouge
:toc-placement!: manual
:pdf-page-size: Letter
:plantumlconfig: plantuml.cfg
endif::[]
ifndef::backend-pdf[]
:toc-placement: manual
endif::[]
:experimental:
:reproducible:
:toclevels: 4
:sectnums:
:sectnumlevels: 3
:encoding: utf-8
:lang: en
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:env-github:

{zwsp} +

ifndef::backend-pdf[]

image::bareboat-necessities-logo.svg[Bareboat Necessities Logo]

{zwsp} +

endif::[]

https://bareboat-necessities.github.io

https://github.com/bareboat-necessities/lysmarine_gen

https://github.com/bareboat-necessities/lysmarine_gen/issues

https://bareboat-necessities.wixsite.com/my-bareboat

{zwsp} +

PDF version:

https://bareboat-necessities.github.io/my-bareboat/bareboat-os.pdf


{zwsp} +

toc::[]


== Getting Started

=== Download Image

Download SD card image (~2.5 Gb file):

https://github.com/bareboat-necessities/lysmarine_gen#download

==== 32-bit vs 64-bit images

- There are pros and cons to each
- 32-bit takes less memory but runs slower
- 32-bit is more supported at the moment (Some cameras not supported on 64-bit yet at the time of writing this)
- QtVlm, wx2img, many OpenCPN plugins are 32-bit only (at the time of writing this)
- You still can run 64-bit kernel with 32-bit image, user space programs will be 32-bit. (Add arm_64bit=1 into /boot/config.txt)
- 32-bit is available on more hardware
- 64-bit OS and OpenCPN are working fine but technically still called 'beta'
- Most of the open (minor) issues are present in both 32 and 64-bit images

NOTE: Switch from 32-bit kernel to 64-bit kernel has an impact on java installation.
See (workaround): https://github.com/bareboat-necessities/lysmarine_gen/issues/44

=== Prepare SD Card

Write the downloaded image to SD card. You can use Raspberry Pi Imager for that:

https://www.raspberrypi.org/software/

If your screen resolution is lower than 1024x600 you would need to manually
set it in /boot/config.txt file, by mounting /boot partition of your SD card
(on windows its done just by inserting it into SD card slot and editing in a plain text
editor).

=== First Boot from SD Card

Insert SD card into raspberry pi SD card slot and power on.
Wait for boot process to run GUI (about 2 mins).

=== Setting up Network

==== Wired Ethernet

If you have wired ethernet router you can just plug-in your raspberry pi ethernet port into the
router

==== WiFi Client

Go into network settings menu and delete WiFi wireless access point.

NOTE: You need to set up WiFi country.

Change /etc/wpa_supplicant/wpa_supplicant.conf to add line for your country (example):

[source]
----
country=US
----

Change /etc/default/crda to set your country (example):

[source]
----
REGDOMAIN=US
----

When raspberry pi WiFi card discovers your WiFi router network click to connect to wifi
and enter the correct WiFi password.

==== WiFi Access Point

Wi-Fi connections managed by widely used Gnome NetworkManager. Look for 'nmcli' documentation
(command line interface to NetworkManager).

==== Typical Setup on a Boat

* Raspberry Pi wired to OpenWrt LTE/4G/WiFi router via ethernet port
* Raspberry Pi provides 5GHz WiFi 802.11ac local access point for boat local WiFi network
* OpenWrt LTE/4G/WiFi router provides WiFi connection to marinas
* OpenWrt LTE/4G/WiFi router provides access to the Internet via LTE/4G cellular data network
* OpenWrt LTE/4G/WiFi router provides 2.4GHz (WiFi 802.11n) local access point for boat IoT devices
* OpenWrt LTE/4G/WiFi router serves as firewall

If you use raspberry pi WiFi it is better to disable WiFi power management:

[source, shell]
----
sudo systemctl unmask wifi_powersave@off.service
sudo systemctl enable wifi_powersave@off.service
sudo systemctl start wifi_powersave@off.service
----

=== Set Timezone / Locale

Open Terminal from GUI and on the terminal command line:

[source, shell]
----
cd ~/add-ons
./timezone-setup.sh
----

For changing locale (ex: to en_US.UTF-8):
[source, shell]
----
sudo su
perl -pi -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen en_US.UTF-8
update-locale en_US.UTF-8
----

=== Change Password

Open Terminal from GUI and on the terminal command line:

[source, shell]
----
cd ~/add-ons
./change-password.sh
----

=== International Keyboard

Keyboard layout controlled by pre-installed ibus application. To add a language:

[source, shell]
----
ibus-setup
----

I also disable it from showing up in system tray, and I rely on switching languages using
onboard keyboard Win-Space key combo.

=== SSD Boot

If you have an SSD drive, and you would like to boot from it (which would be a better way, and
it would greatly improve the performance of the system) then you can follow the steps below:

The OS image comes with utility called 'rpi-clone' preinstalled. If you have a custom case
for your raspberry pi (Ex. DeskPi Pro), then you would need to install vendor drivers for your
case per vendor instructions.

Open Terminal from GUI and your command line for rpi-clone should look like
(check usage https://github.com/billw2/rpi-clone as there might be nuances for your particular
set up):

[source, shell]
----
sudo rpi-clone sda
----

Follow the prompts.

=== Set up GPS

Plugin your GPS USB mouse and OS should recognize it. Check:

[source, shell]
----
ls -l /dev/ttyLYS*
----

=== Set up AIS

Plugin your dAISy AIS receiver into USB and OS should recognize it. Check:

[source, shell]
----
ls -l /dev/ttyLYS*
----

=== Update OpenCPN Plugins

* Start OpenCPN
* Go to Tools/Options/Plugins
* Update Plugin Catalog
* Browse plugins list and update plugins when an update available (one by one)

NOTE: Due to a bug in OpenCPN https://github.com/bareboat-necessities/lysmarine_gen/issues/53
Updating plugins on a system booted with arm64 kernel doesn't work even if userspace is armhf.
As a workaround: boot with armhf kernel, update all plugins
and only then switch to arm64 kernel

=== Set up Charts

OS image comes with several chartplotters:

* OpenCPN
* AvNav
* Freeboard-SK
* TukTuk

with extensive set of plugins as well as weather GRIB file viewers

* XyGrib


==== OpenCPN

* Start OpenCPN. Go into Tools/Options/Charts/Chart Downloader tab.
* Click 'Add Catalog'. For USA: click USA NOAA & Inland Charts / ENC / By Region.
* Pick your region, click (or touch) 'OK'
* Click 'Update' (to update the catalog)
* Click 'Download Charts...' tab
* Right-click (or long touch) in the charts list
* Click 'Select all' from the pop-up menu
* Press 'Download selected charts' button, and wait for it to finish
* Press 'Apply' button
* Click 'Chart Files' tab
* Press 'Prepare all ENC Charts' button
* Press 'OK' button when done

O-Charts can be registered using preinstalled OpenCPN plugins (on arm32 user space make sure to update plugins on-line
from OpenCPN catalog) with O-Charts USB dongle or key.

==== AvNav

When you are online NOAA raster MB tiles should work out of the box. O-Charts can be registered using AvNav plugin
with O-Charts USB dongle or key.

==== SignalK, FreeBoard-SK, TukTuk

Follow SignalK documentation to install offline charts for these.

=== SignalK

SignalK manages its own updates. Login into SignalK Marine Data Server web UI application
and perform updates via its app store.

=== PyPilot

Starting PyPilot server:

[source, shell]
----
sudo systemctl enable pypilot@pypilot
sudo systemctl start pypilot@pypilot
----

=== Weather

You can add weather budgie desktop applet. Unfortunately it is linked to a fixed location which is
fine for a day-sailor but doesn't work for others.

Off-shore sailors or even coastal cruisers should focus on using XyGrib and GRIB plugin for OpenCPN.

For real blue water sailors OpenCPN Climatology and OpenCPN weather routing plugins are essential.

=== Music Players

The OS image comes with Mopidy, MPD server, MusicBox, Shairport-Sync (AirPlay) server.
The default audio output set up to audio jack port.

==== MusicBox

Start MusicBox web UI. Try pre-configured playlist, or you can search Tune-In or YouTube.

==== Playing from your iPhone (Spotify, etc)

Play music on iPhone. Select AirPlay on your iPhone and cast to 'lysmarine' airplay target (your phone must be
on lysmarine WiFi).

==== Playing from mobile phones with MPD applications

Install MPD compatible media player on your mobile device and from it you can
control playing your Mopidy library on your raspberry pi.

=== Interfacing with ship systems

The first place to start configuring boat interfaces would be SignalK.
SignalK comes with many plugins to talk to many boat devices with the support of various
protocols.

==== NMEA 0183

If you use FTDI USB serial to USB sticks the OS should recognize them right away,
and if they are wired correctly to NMEA devices (ex: wind/depth/speed/GPS) their reading
should automatically show up in instrument dashboards.

==== NMEA 2000

Check SignalK plugin settings and SignalK documentation.

==== IMU

Check PyPilot settings and PyPilot documentation.

General steps are

- enable i2c (Interface options)

[source, shell]
----
cd ~/add-ons
./os-settings.sh
----

- Enable pypilot service

[source, shell]
----
sudo systemctl enable pypilot@pypilot
sudo systemctl start pypilot@pypilot
----

- At this point you should be able to see reading of pitch/roll, etc, and magnetic heading in pypilot control.
Which you would need to calibrate.

- Start pypilot calibration. Press 'Boat Level' when the boat leveled. (Your IMU must be obviously
mounted hard to the boat, can't be just hanging).
For magnetic heading: IMU doesn't know how you oriented it inside (where bow is pointing), so you need to adjust
it by filling magnetic heading adjustment field.

- Establish connection from PyPilot to SignalK.

- Go to SignalK web UI as admin and approve the access request from PyPilot for READ/WRITE access.

- IMU data should start flowing into SignalK


==== Barometer / Temperature / Humidity

Check SignalK plugin settings and SignalK documentation.

General steps are:

- enable i2c (Interface options)

[source, shell]
----
cd ~/add-ons
./os-settings.sh
----

- To check if it's working:

[source, shell]
----
lsmod | grep i2c-dev
i2cdetect 1
----

- Login into SignalK Marine Data Server

- Enable BMP or BME sensor plugin. Give it correct i2c address. Reduce poll timeout to 20 sec. Restart SignalK server.

- At this point you should be able to see barometric pressure and temperature (possibly humidity)
in your data feed.

==== Other

Many other devices are supported (usually via SignalK)

=== Instrument Dashboards

==== OpenCPN

Enable OpenCPN 'Dashboard' plugin, add instruments. Dashboards are dockable to the right on bottom of OpenCPN canvas.

==== KIP

* Load KIP demo. In setting of KIP dashboard change the URL to http://localhost
* You should request KIP token to be registered in SignalK, then go into SignalK app and
authorize it. After that edit instruments and layout in KIP dashboard settings.

=== Remote Access

==== VNC

OS image comes with VNC pre configured. You can change default password by removing
/home/user/.vnc/passwd file and accessing VNC server from client. On the first login
it will prompt to set up a new password.

OS image also provides VNC client app.

==== ssh

OS image comes with ssh enabled. You can log in using ssh user: 'user'.

=== Marine Radio

OS image comes with many HAM radio applications, decoders for many marine specific
signals and protocols. Many SDR products should work. Decoding is also possible using
external HAM receivers connected via sound input port (USB sound card required as raspberry pi
doesn't have built-in sound input). Proper antennas required for correct reception.

=== Cameras

==== IP Cameras

Should be easy to integrate using pre-installed VLC.
See URL in /var/www/bbn-launcher/bbn-launcher.js

==== MotionEye

By default, motioneye service installed and enabled. To disable:

[source, shell]
----
sudo systemctl disable motioneye
sudo systemctl stop motioneye
sudo systemctl status motioneye
----

Default user: admin

Password is empty.

=== Cruising within Cellular Phone Reception

Adding some OpenWrt LTE/4G router greatly improves your boat connectivity to
the world near shore. You should definitely do it to have internet access from your boat.

The OS image gives you internet applications for:

* Email
* Chat
* Facebook
* YouTube
* Browser
* On-Line Weather
* On-Line Charts
* Marina Booking
* Sailing Education
* SMS
* and much more

=== Offshore Features

For offshore sailors there are number of features pre-loaded into the OS image

* NavTex
* Inmarsat Fleet (receiving messages)
* Using Iridium as modem
* WeatherFax
* GRIB (could be over SSB)
* AirMail / WinLink
* SDR / HAM Radio Apps
* AIS
* Weather Routing / Climatology
* Celestial Navigation
* Autopilot (PyPilot)
* Satellite Weather
* Radars (several supported)
* Location Reporting

They do require additional hardware, set up and dedication.

=== Watching Movies

Watching on-line (or listening) prepaid copyrighted content (Netflix, Amazon PrimeVideo, Google, Spotify, etc) in
a web browser as Chromium requires closed-source DRM libraries. On arm32 version of the OS you can install it
from add-ons folder ~/add-ons/ by running:

[source, shell]
----
./widevine-lib-install.sh
----

NOTE: As of moment of writing this procedure doesn't work on arm64. It does work on arm32, and even on
arm32 with 64-bit kernel.

=== How it is Made

For those who are comfortable writing software the scripts to create this image
stored on the image itself (for the reference) in /install_scripts.
The full source code to create the image is available at: <https://github.com/bareboat-necessities/lysmarine_gen>

=== Shutting Down / Rebooting

On the desktop click arrow to get to the second set of desktop icons.
Click on the 'Commands' icon. You will see a menu from where
you can perform restart/shutdown, and more.

==== Safe Power-Down

Raspberry pi doesn't have a safe power-off feature. I.e. it doesn't perform OS shutdown before
powering off with a button. There are numerous third-party solutions with raspberry pi hats or
custom cases. Make sure you do not forget to install required software for them per vendor documentation.

=== Customizing Desktop

Desktop can be customized by editing the JavaScript file in /var/www/bbn-launcher.

=== Customizing On First Boot

You can add additional customizations which will be performed on system first boot by
mounting OS image and editing /boot/first-boot.sh script. That script as its name suggests
executes only once on the first boot.

=== Known Issues and Workarounds

See: https://github.com/bareboat-necessities/lysmarine_gen/issues

==== Touchscreen

* Some applications (namely OpenCPN and gtk2 based as well as some Qt) sometimes stop responding to touch events.
There is a workaround. With your finger you can toggle maximized mode via window frame icon then you
MOVE the window frame by dragging window header few pixels, and switch back to maximized mode if needed.
This should restore touch events in that app.

* Some gtk3 applications menus (ex: terminal) have issues handling touch events. You can select a menu item
with touch but to perform a click on it you would actually need to perform simulated right click
by holding finger a bit longer and letting it go.

=== Add-ons

Check /home/user/add-ons directory. It contains number of scripts for installing many additional programs
which for one or another reason couldn't be a part of the distribution image.

=== Suggestions

The beauty of Linux is that you can customize it for your needs in infinite ways.
While this distro aimed to strike common need, you will find that number of post-install
customization steps would be required. The key is to script those steps, make them non-interactive,
make the steps requite NO GIU. In that case your set up becomes RE-PRODUCIBLE in case of new
OS image releases. You can share your post-install scripts, so the system can be improved and even more fine-tuned.

=== Hardware

This is not my first build of the boat computer with raspberry pi. A lot of ideas can be taken from my
older (2020 build which was based on OpenPlotter). For up-to-date build I would change few things:

* Instead of expensive Argonaut M7 I would have used
(Model: SL07W, Brand Sihovision, Capacitive Touch Screen 7 inch, (1000 nits), IP65, 1024x600, Cost under $300):
https://www.sihovision.com/industrial-touch-monitor/7-inch-industrial-wide-temperaturer-lcd-monitor-with-remote-control-1.html

* My waterproofing technique would be cheaper and better. Instead of costly connectors at the back of the computer (even if it is below deck)
I would use waterproof glands for exits from the enclosure and pigtail connectors. I would cover the point of connection with heat shrink tubing.

* I would have used some kind of safe power-off solution and SSD instead of just SD card. SSD gives HUGE performance gain.

* I would use this OS image (instead of OpenPlotter image)

* dAISy AIS is better solution than SDR

For older hardware solutions (lot of it is still valid) see:

https://bareboat-necessities.github.io/my-bareboat/

=== HOWTOs

Please send us your HowTo, and we can add it here for everyone to find. Thanks

