= Estimating wave height from IMU accelerometer on a moving boat (Early Draft)
mgrouch <mgrouch@users.noreply.github.com>
{docdate}, Wave Height from IMU accelerometer
:imagesdir: images
:doctype: book
:organization: Bareboat Necessities
:description: Bareboat Necessities, Wave Height from IMU accelerometer
:title-logo-image: image:bareboat-necessities-logo.svg[Bareboat Necessities Logo]
ifdef::backend-pdf[]
:source-highlighter: rouge
:toc-placement!: manual
:pdf-page-size: Letter
:plantumlconfig: plantuml.cfg
endif::[]
ifndef::backend-pdf[]
:toc-placement: manual
endif::[]
:stem:
:experimental:
:reproducible:
:toclevels: 4
:sectnums:
:sectnumlevels: 3
:encoding: utf-8
:lang: en
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:env-github:

{zwsp} +

ifndef::backend-pdf[]

image::bareboat-necessities-logo.svg[Bareboat Necessities Logo]

{zwsp} +

== Abstract

Usual methods for measuring elevation built-in into modern smartwatches and smart devices are based on fusion of data
(using Kalman filters, etc) from IMU (accelerometer) and barometer sensors. These methods are designed to measure steps up and down stairs,
hiking activities, and so on. However, using pressure as a useful source of elevation data is not suitable to measure
the wave height from a boat. The surface of the wave itself (at least in trochoidal wave model) is the surface of
equal pressure. Real waves are more complicated but nevertheless measuring air pressure on their surface
to estimate amplitude of the wave would lead to measuring mostly noise.

Calculating elevation (displacement) using double integration of the acceleration leads
to huge result drift due to not knowing initial displacement, initial vertical velocity
and due to signal noise and accelerometer bias.

This article describes two different methods to estimate wave height, frequency, period
from a moving boat using IMU (accelerometer) and other common boat sensors such as anemometer (wind), GPS, and compass.
One method is based on Kalman method which calculates second integral of acceleration with a drift correction
based on the fact that in wave average displacement equals to zero. Another method doesn't use
integration at all. Instead, it measures max/min acceleration and assumes wave shape to be trochoidal.
Based on max/min acceleration and observed wave frequency (later adjusted using Doppler effect formulas)
the method recreates parameters of the trochoid wave allowing it to estimate the wave height.

== Trochoidal Waves

Gravitational {nbsp} stem:[g] {nbsp} (m/s^2): {nbsp}{nbsp}{nbsp}
stem:[g = 9.81]

Rotation center of trochoidal wave particle in Z axis (always negative) (m): {nbsp}{nbsp}{nbsp}
stem:[b]

Wavelength (m): {nbsp}{nbsp}{nbsp}
stem:[L]

Wave equation:

stem:[X(t) = H sin(k c t) + c t]

stem:[Z(t) = - H cos(k c t)]

Wavenumber (1/m): {nbsp}{nbsp}{nbsp}
stem:[k = (2 pi) / L]

Wave amplitude (m):  {nbsp}{nbsp}{nbsp}
stem:[H = e ^(k b) / k = L / (2 pi) e ^ ((2 pi b) / L)  ] {nbsp}{nbsp}{nbsp} => {nbsp}{nbsp}{nbsp}
stem:[b = L / (2 pi) ln ((2 pi H) / L)  ]

max(H) amplitude (m):   {nbsp}{nbsp}{nbsp}  stem:[H_max = L / (2 pi)] {nbsp}{nbsp}{nbsp} when {nbsp} b = 0

Depth (m): {nbsp}{nbsp}{nbsp}
stem:[d]

Wave speed (m/s): {nbsp}{nbsp}{nbsp}
stem:[c = sqrt(g / k tanh(k d))] {nbsp},{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}
for deep water waves: stem:[c = sqrt(g / k) = sqrt((g L) / (2 pi) )],  {nbsp}{nbsp} stem:[L = (g T ^ 2) / (2 pi)]

Wave period (s):   {nbsp}{nbsp}{nbsp}
stem:[T = L / c]

Wave frequency (Hz=1/s):   {nbsp}{nbsp}{nbsp}
stem:[f = 1 / T = c / L]

Vertical velocity (m/s):

stem:[v(t) = c (dZ / dx) =  c (dZ/dt) / (dX/dt) = c (Hk sin(ckt)) / ( Hk cos(ckt) + 1)]


Vertical acceleration (m/s^2):

stem:[a(t) = v^'(t) = d^2 Z / x^2 = dv / dx =  (dv/dt) / (dX/dt) = (Hc^2k^2 cos(ckt)) / ( Hk cos(ckt) + 1) ]

Third derivative (m/s^3):

stem:[a^'(t) = d^3 Z / x^3 = da / dx =  (da/dt) / (dX/dt) = - (Hc^3k^3 sin(ckt)) / ( Hk cos(ckt) + 1) ]

stem:[t] where stem:[a^'(t) = 0]

stem:[t = pi (2 N + 1) / (ck), t = pi (2 N) / (ck)]

stem:[a_max = (Hc^2k^2) / ( 1 + Hk) = (g L) / (2 pi)  (e^((2pib)/L)) / (1 + e^((2pib)/L)) (2 pi) / L = g / (e^(-(2pib)/L) + 1) ]

stem:[a_min = (Hc^2k^2) / ( 1 - Hk) = g / (e^(-(2pib)/L) - 1) ]

Doppler effect:

stem:[f_o] observed frequency (Hz=1/s)

stem:[L_s] source wavelength (m)

stem:[L_s = (sign(Delta v) sqrt(8 pi f_o g  Delta v + g ^ 2) + 4 pi f_o  Delta v + g) / (4 pi f_o ^ 2)]

stem:[b = L *

== Measuring wave height from a moving boat

endif::[]
