= Bareboat Necessities OS Documentation
mgrouch <mgrouch@users.noreply.github.com>
{docdate}, Bareboat Necessities OS Documentation
:imagesdir: images
:doctype: book
:organization: Bareboat Necessities
:title-logo-image: image:bareboat-necessities-logo.svg[Bareboat Necessities Logo]
ifdef::backend-pdf[]
:source-highlighter: rouge
:toc-placement!: manual
:pdf-page-size: Letter
:plantumlconfig: plantuml.cfg
endif::[]
ifndef::backend-pdf[]
:toc-placement: manual
endif::[]
:experimental:
:reproducible:
:toclevels: 4
:sectnums:
:sectnumlevels: 3
:encoding: utf-8
:lang: en
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:env-github:

{zwsp} +

ifndef::backend-pdf[]

image::bareboat-necessities-logo.svg[Bareboat Necessities Logo]

{zwsp} +

endif::[]

https://bareboat-necessities.github.io

https://github.com/bareboat-necessities/lysmarine_gen

https://github.com/bareboat-necessities/lysmarine_gen/issues

https://bareboat-necessities.wixsite.com/my-bareboat

{zwsp} +

PDF version:

https://bareboat-necessities.github.io/my-bareboat/bareboat-os.pdf


{zwsp} +

toc::[]


== Getting Started

=== Why use BBN OS?

Why use BBN OS? Some people use just commercial marine electronics on board, some ones use smart tablets and marine
Wi-Fi multiplexers. All these solutions lack one important component - an onboard computer capable of monitoring
and controlling all aspects of the boat systems, and capable of storing data. Some people put Intel-based computer for that.
Intel-based solutions are more power consuming. With BBN OS you can build a central boat computer meeting your needs.
All on low power consuming raspberry pi with flexibility of adding countless choices of sensors to talk to
all boat systems, Internet, local Wi-Fi, cameras, NMEA network, and a system able to decode marine radio protocols.
BBN OS is free and open source. It is based on commonly used community supported open source projects such as SignalK,
PyPilot, OpenCPN, and others. BBN OS graphical user interface will let you build a cockpit front-end to all functionality
of the OS from chartplotting, dashboards, weather information, to media player, etc.

==== Use Cases

* Cockpit Touchscreen Chartplotter
* Nav Station Computer
* Desktop Computer
* Pi Based Laptop
* Headless Server
* Media Player
* Autopilot
* SSB Radio Decoder
* Marine Data Server, Multiplexer
* Wi-Fi Access Point
* Cameras Monitoring
* Data Analytics Server
* Weather Station
* Boat Dashboards
* File Server

==== Smart Boat

.Smart Boat Diagram
ifdef::env-github[image::system-arch.svg[Smart Boat]]
ifndef::env-github[]

[plantuml,system-arch,svg]
....
!include plantuml/system-arch.puml
....

endif::[]

{zwsp} +
{zwsp} +

=== Download Image

Download SD card image (~2.5 Gb file):

https://github.com/bareboat-necessities/lysmarine_gen#download

Alternative place to download if the previous link doesn't work for you:

https://archive.org/details/lysmarine-bbn-linux-LTS


==== 32-bit vs 64-bit images

- There are pros and cons to each
- 32-bit takes less memory but runs slower
- 32-bit is more supported at the moment (Some cameras not supported on 64-bit yet at the time of writing this)
- QtVlm, wx2img, many OpenCPN plugins are 32-bit only (at the time of writing this)
- You still can run 64-bit kernel with 32-bit image, user space programs will be 32-bit. (Add arm_64bit=1 into /boot/config.txt)
- 32-bit is available on more hardware
- 64-bit OS and OpenCPN are working fine but technically still called 'beta'
- Most of the open (minor) issues are present in both 32 and 64-bit images

NOTE: Switch from 32-bit kernel to 64-bit kernel has an impact on java installation.
See (workaround): https://github.com/bareboat-necessities/lysmarine_gen/issues/44

So as of time of writing this the best performance/compatibility is the 32-bit image with the kernel switched to 64-bit.

- Install 32-bit image
- Upgrade and install all additional plugins for OpenCPN via OpenCPN plugin downloader after updating the catalog.
- Switch to 64-bit kernel in /boot/config.txt
- Proceed with all other configuration steps.

=== Prepare SD Card

Write the downloaded image to SD card. Minimum 32Gb SD card recommended.
You can use Raspberry Pi Imager for that:

https://www.raspberrypi.org/software/

If your screen resolution is lower than 1024x600 you would need to manually
set it in /boot/config.txt file, by mounting /boot partition of your SD card
(on windows its done just by inserting it into SD card slot and editing in a plain text
editor).

Quality of SD card is essential for performance of your system. BBN OS comes
with disk benchmarking tool. Good SD card would show about 45 MB/sec (or higher) read i/o speed in it.
SSD drives would show much better results: 178 MB/sec read and 147 MB/sec write i/o speed or higher.

=== First Boot from SD Card

Insert SD card into raspberry pi SD card slot and power on.
Wait for boot process to run GUI (about 2 mins).

=== Setting up Network

==== Wired Ethernet

If you have wired ethernet router you can just plug-in your raspberry pi ethernet port into the
router

==== Wi-Fi Client

Go into network settings menu and delete Wi-Fi wireless access point.

NOTE: You need to set up Wi-Fi country.

Change /etc/wpa_supplicant/wpa_supplicant.conf to add line for your country (example):

[source]
----
country=US
----

Change /etc/default/crda to set your country (example):

[source]
----
REGDOMAIN=US
----

When raspberry pi Wi-Fi card discovers your Wi-Fi router network click to connect to Wi-Fi
and enter the correct Wi-Fi password.

When password storage manager pops up to enter the password for your password storage I just normally leave it blank, so
I'm not prompted again.

==== Wi-Fi Access Point

Wi-Fi connections are managed by widely used Gnome NetworkManager. Look for 'nmcli' documentation
(command line interface to NetworkManager). Or you can figure it out from Administration/Advanced Network Settings
app menu. By default, OS image is set up to provide you an access point.

[#tether]
==== Using iPhone as Internet gateway

Enable Personal Hotspot on iphone. Plug it in into pi with BBN OS via USB and tell iPhone to trust the connected computer.
You will have a tethered Internet connection from your pi via iPhone (using usbmuxd).

You do not have to be plugged in into USB if your phone, and a boat computer are on the same local
Wi-Fi network.

[#tether_android]
==== Using Android phone as Internet gateway

Enable USB tethering in network settings on your Android phone. Plug it into your boat computer via USB.

The output of the command below should show a new route via usb0 interface:
[source, shell]
----
netstat -nr
----

You can also do tethering via Wi-Fi instead of USB.

==== SpaceX Starlink

SpaceX Starlink Dishy is coming to boats soon and is easy to support.
Power usage might be relatively high for small boats.

==== Typical Setup on a Boat

* Raspberry Pi wired to OpenWrt LTE/4G/WiFi router via ethernet port
* Raspberry Pi provides 5GHz WiFi 802.11ac local access point for boat local WiFi network
* OpenWrt LTE/4G/WiFi router provides WiFi connection to marinas
* OpenWrt LTE/4G/WiFi router provides access to the Internet via LTE/4G cellular data network
* OpenWrt LTE/4G/WiFi router provides 2.4GHz (WiFi 802.11n) local access point for boat IoT devices
* OpenWrt LTE/4G/WiFi router serves as firewall

If you use raspberry pi WiFi it is better to disable WiFi power management:

[source, shell]
----
sudo systemctl unmask wifi_powersave@off.service
sudo systemctl enable wifi_powersave@off.service
sudo systemctl start wifi_powersave@off.service
----

NOTE: It is important to protect your installation from unauthorized access from the Internet. Make sure you put your
raspberry pi behind a router which adds a firewall protection. It is also important to change default passwords.

=== Set Timezone / Locale

Open Terminal from GUI and on the terminal command line:

[source, shell]
----
cd ~/add-ons
./timezone-setup.sh
----

For changing locale (ex: to en_US.UTF-8):
[source, shell]
----
sudo su
perl -pi -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen en_US.UTF-8
update-locale en_US.UTF-8
----

=== Change Password

Default user and root passwords are changeme. You would want to modify it before your computer connects on-line to
the Internet.

Open Terminal from GUI and on the terminal command line:

[source, shell]
----
cd ~/add-ons
./change-password.sh
----

To change root password:

[source, shell]
----
sudo su
passwd
exit
----

=== International Keyboard

Keyboard layout controlled by pre-installed ibus application. To add a language:

[source, shell]
----
ibus-setup
----

I also disable it from showing up in system tray, and I rely on switching languages using
onboard keyboard Win-Space key combo.

=== SSD Boot

If you have an SSD drive, and you would like to boot from it (which would be a better way, and
it would greatly improve the performance of the system) then you can follow the steps below:

The OS image comes with utility called 'rpi-clone' preinstalled. If you have a custom case
for your raspberry pi (Ex. DeskPi Pro), then you would need to install vendor drivers for your
case per vendor instructions.

Open Terminal from GUI and your command line for rpi-clone should look like
(check usage https://github.com/billw2/rpi-clone as there might be nuances for your particular
set up):

[source, shell]
----
sudo rpi-clone sda
----

Follow the prompts.

=== Set up GPS

Plugin your GPS USB mouse and OS should recognize it. Check:

[source, shell]
----
ls -l /dev/ttyLYS*
----

=== Set up AIS

Plugin your dAISy AIS receiver into USB and OS should recognize it. Check:

[source, shell]
----
ls -l /dev/ttyLYS*
----

=== Update OpenCPN Plugins

* Start OpenCPN
* Go to Tools/Options/Plugins
* Update Plugin Catalog
* Browse plugins list and update plugins when an update available (one by one)

NOTE: Due to a bug in OpenCPN https://github.com/bareboat-necessities/lysmarine_gen/issues/53
Updating plugins on a system booted with arm64 kernel doesn't work even if userspace is armhf.
As a workaround: boot with armhf kernel, update all plugins
and only then switch to arm64 kernel.

=== Set up Charts

OS image comes with several chartplotters:

* OpenCPN
* AvNav
* Freeboard-SK
* TukTuk

with extensive set of plugins as well as weather GRIB file viewers

* XyGrib

=== Set up your Ship Parameters

Do not forget to set up your ship parameters in SignalK and Vessel applications.
They can come handy.

==== OpenCPN

* Start OpenCPN. Go into Tools/Options/Charts/Chart Downloader tab.
* Click 'Add Catalog'. For USA: click USA NOAA & Inland Charts / ENC / By Region.
* Pick your region, click (or touch) 'OK'
* Click 'Update' (to update the catalog)
* Click 'Download Charts...' tab
* Right-click (or long touch) in the charts list
* Click 'Select all' from the pop-up menu
* Press 'Download selected charts' button, and wait for it to finish
* Press 'Apply' button
* Click 'Chart Files' tab
* Press 'Prepare all ENC Charts' button
* Press 'OK' button when done.

O-Charts can be registered using preinstalled OpenCPN plugins (on arm32 user space make sure to update plugins on-line
from OpenCPN catalog) with O-Charts USB dongle or key.

==== AvNav

When you are online NOAA raster MB tiles should work out of the box. O-Charts can be registered using AvNav plugin
with O-Charts USB dongle or key.

==== SignalK, FreeBoard-SK, TukTuk

Follow SignalK documentation to install offline charts for these.

=== SignalK

SignalK manages its own updates. Login into SignalK Marine Data Server web UI application
and perform updates via its app store.

For SignalK support visit: https://signalk-dev.slack.com/

=== PyPilot

Starting PyPilot server:

[source, shell]
----
sudo systemctl enable pypilot@pypilot
sudo systemctl start pypilot@pypilot
----

Apart from the official PyPilot documentation you will find this WiKi
https://github.com/pypilot/workbook/wiki very useful as well.

=== Weather

You can add weather budgie desktop applet. Unfortunately it is linked to a fixed location which is
fine for a day-sailor but doesn't work for others.

Off-shore sailors or even coastal cruisers should focus on using XyGrib and GRIB plugin for OpenCPN.

For real blue water sailors OpenCPN Climatology and OpenCPN weather routing plugins are essential.

==== GRIB

Launch xyGrib. Select an area on the map. Click to download Grib file.
Choose Atmospheric Model and Wave Model. Pick Wind, Wind Gust options in Surface Data
and Wave Height in Wave Data. Click Download.
Save Grib data file somewhere under user home.
(Do not put it into .xygrib hidden directory as OpenCPN GRIB plugin can't look there).

Now you can overlay this GRIB data on OpenCPN chart.
Enable GRIB plugin in OpenCPN. Click on GRIB plugin in OpenCPN plugin toolbar.
Load GRIB file into OpenCPN. See weather data overlayed over your chart.

OpenCPN GRIB plugin can also prepare SailMail email requests for Grib files.
You can store them and email via Internet (if you have connection) or use
WinLink Pat (WinLink client: https://github.com/la5nta/pat/wiki).

==== NOAA weather in SignalK

SignalK comes with NOAA weather plugin. After you configure it, weather alerts will
show up in KIP dashboard.

==== WeatherFax

WeatherFax OpenCPN plugin is capable of downloading weather faxes from Internet as well as capturing
them from SSB radio via audio input. (Pi needs a sound card with audio input because it is sold without
audio input card). Just as GRIB files they can be overlaid over charts.

==== Weather routing

Weather routing OpenCPN plugin is able to plan your trip route. It uses your boat polar diagram, so
make sure you have built it in advance using Polar plugin.

You also need to download climatology data using OpenCPN climatology plugin, and
download a grib file. They are also needed and used in weather routing.


=== WinLink (SailMail analogue) for Raspberry Pi

To install:

[source, shell]
----
cd ~/add-ons
./sailmail-pat-install.sh
----

Documentation on setting it up and using it:

https://github.com/la5nta/pat/wiki
https://getpat.io/

Video Series:
Winlink on a Raspberry Pi
https://www.youtube.com/playlist?list=PL1QTYT4Qo9cY98NFmxrTvtGyWI9pgxtFq

=== Music Players

The OS image comes with Mopidy, MPD server, MusicBox, Shairport-Sync (AirPlay) server.
The default audio output set up to audio jack port.

==== MusicBox

Start MusicBox web UI. Try pre-configured playlist, or you can search Tune-In or YouTube.

==== Iris

Iris is an alternative player to MusicBox. Iris is also included in the BBN OS image.

==== Playing from your iPhone (Spotify, etc)

Play music on iPhone. Select AirPlay on your iPhone and cast to 'lysmarine' airplay target (your phone must be
on lysmarine-hotspot WiFi).

==== Playing from mobile phones with MPD applications

Install MPD compatible media player on your mobile device and from it you can
control playing your Mopidy library on your raspberry pi.

==== Playing Spotify

Start yoour Spotify app on your mobile device which is connected to boat WiFi.
Select 'Lysmarine' device as target to play on pi via raspotify. You need to have a premium Spotify account.

=== Interfacing with ship systems

The first place to start configuring boat interfaces would be SignalK.
SignalK comes with many plugins to talk to many boat devices with the support of various
protocols.

==== NMEA 0183

If you use FTDI USB serial to USB sticks the OS should recognize them right away,
and if they are wired correctly to NMEA devices (ex: wind/depth/speed/GPS) their reading
should automatically show up in instrument dashboards.

==== NMEA 2000

Check SignalK plugin settings and SignalK documentation.

==== IMU

Check PyPilot settings and PyPilot documentation.

General steps are

- enable i2c (Interface options)

[source, shell]
----
cd ~/add-ons
./os-settings.sh
----

- Enable pypilot service

[source, shell]
----
sudo systemctl enable pypilot@pypilot
sudo systemctl start pypilot@pypilot
----

- At this point you should be able to see reading of pitch/roll, etc, and magnetic heading in pypilot control.
Which you would need to calibrate.

- Start pypilot calibration. Press 'Boat Level' when the boat leveled. (Your IMU must be obviously
mounted hard to the boat, can't be just hanging).
For magnetic heading: IMU doesn't know how you oriented it inside (where bow is pointing), so you need to adjust
it by filling magnetic heading adjustment field.

- Establish connection from PyPilot to SignalK (restart PyPilot just before doing it to get a fresh valid request)

- Go to SignalK web UI as admin and approve the access request from PyPilot for READ/WRITE access.

- IMU data should start flowing into SignalK


==== Barometer / Temperature / Humidity

Check SignalK plugin settings and SignalK documentation.

General steps are:

- enable i2c (Interface options)

[source, shell]
----
cd ~/add-ons
./os-settings.sh
----

- To check if it's working:

[source, shell]
----
lsmod | grep i2c-dev
i2cdetect 1
----

- Login into SignalK Marine Data Server

- Enable BMP or BME sensor plugin. Give it correct i2c address. Reduce poll timeout to 20 sec.

- Change 'salon.inside' to 'outside' (one word) for OpenCPN to display readings.

- Restart SignalK server.

- At this point you should be able to see barometric pressure and temperature (possibly humidity)
in your data feed.

==== Other

Many other devices are supported (usually via SignalK)

=== Instrument Dashboards

==== OpenCPN

Enable OpenCPN 'Dashboard' plugin, add instruments. Dashboards are dockable to the right on bottom of OpenCPN canvas.

==== KIP

* Load KIP demo. In setting of KIP dashboard change the URL to http://localhost:3000
* You should request KIP token to be registered in SignalK, then go into SignalK app and
authorize it. After that edit instruments and layout in KIP dashboard settings.

=== Remote Access

==== VNC

BBN OS image comes with RealVNC server pre-installed and ready to be used on the local network.

IMPORTANT: You need to change the authentication method or the default unix user password before connecting the
system to the Internet.

OS image also provides VNC client app.

===== RealVNC with cloud connectivity

Create an account on realvnc.com website. Login from your pi's RealVNC server into
realvnc.com cloud using the account you set up. Set-up a password on your pi's VNC server for
users to connect. While being logged in into realvnc.com website create a team and invite
people you want to have remote desktop access to your pi. When they accept your invite
let them know the password to connect to your local VNC server. They would need to download
realVNC viewer (can be for PC, Linux, Mac, etc) and follow the instructions from the invite.

==== ssh

OS image comes with ssh enabled. You can log in using ssh user: 'user'.

==== Android Devices

OS image comes with scrcpy pre-installed and pre-configured. You can view and control your Android devices.
You need to enable USB debugging on your Android device or follow the instructions
to enable controlling it via WiFi. See: https://github.com/Genymobile/scrcpy
In most cases you just need to enable USB debugging on your Android device and plug it in (thanks to autoadb).

==== Browsers

The URLs of the applications on your boat computer:

* http://lysmarine:8080 PyPilot
* http://lysmarine:3000 SignalK
* http://lysmarine:3000/@mxtommy/kip/ KIP
* http://lysmarine:3000/@signalk/signalk-node-red Node Red
* http://lysmarine:3000/admin/#/e/_signalk_vesselpositions Vessels Positions
* http://lysmarine:3000/tuktuk-chart-plotter/ TukTuk Chartplotter
* http://lysmarine:3000/@signalk/signalk-autopilot/ SK Autopilot
* http://lysmarine:3000/@signalk/freeboard-sk SK Freeboard
* http://lysmarine:8099 AvNav
* http://lysmarine:6680 Mopidy
* http://lysmarine:6680/musicbox_webclient/ Mopidy MusicBox
* http://lysmarine:6680/iris/ Mopidy Iris
* http://lysmarine:8765 MotionEye Cameras

Make sure your lysmarine computer is mapped to a static IP address on your network via MAC address mapping on your router.

==== Casting from Chromium to your TV

You can start Chromium and cast browser tab or whole desktop to your smart TV via ChromeCast protocol
using Chromium menu 'Cast' option and selecting an appropriate source. Your TV and your boat computer need to be
on the same network (LAN or Wi-Fi).

==== SmartPhone Applications

There are many applications for smartphones which will take live NMEA data stream from your boat computer
host: lysmarine, port: 10110.

There are several ones which will even discover SignalK and use SignalK protocol. Examples: SignalK Monitor, SignalK.

Your phone and your boat computer need to be on the same Wi-Fi network.

=== Headless Operation

It's possible to disable booting into GUI by running:

[source, shell]
----
sudo raspi-config
----

and selecting booting into the console under System Options / Boot - Auto Login.


=== Marine Radio

OS image comes with many HAM radio applications, decoders for many marine specific
signals and protocols. Many SDR products should work. Decoding is also possible using
external HAM receivers connected via sound input port (USB sound card required as raspberry pi
doesn't have built-in sound input). Proper antennas required for correct reception.

HAM Radio menu contains a few applications useful especially for offshore sailors.
If you do not have a cellular or a satellite connection, you still have SSB (and if you installed it SDR) radio.
These applications will allow you (with some skill and set up):

- Receive weather GRIBs via WinLink
- Receive and decode WeatherFax, NavTex, NOAA and satellite weather images, Inmarsat Fleet messages
- Send and receive emails via WinLink (requires you to have a HAM amateur radio license)
- SDR can help you to decode AIS, and ADS-B (aviation analogue of AIS)
- and more


=== Iridium Phone

BBN OS will help you to use Iridium Phone as a modem for low bandwidth Internet access, or
to send periodic short burst data with use of a specially written SignalK plugin.

=== Cameras

==== IP Cameras

Should be easy to integrate using pre-installed VLC.
See URL in /var/www/bbn-launcher/bbn-launcher.js

IP cameras usually have some delay in video display.

==== Connecting cameras to CSI on raspberry pi

Geekworm Raspberry Pi Hdmi-in Module, Hdmi to CSI-2 could be used to solve distance issue with CSI cameras.

https://geekworm.com/products/raspberry-pi-hdmi-to-csi-2-adapter-board-with-15-pin-ffc-cable

Another trick with Arducam CSI to HDMI Cable extension is for CSI cameras to connect to raspberry pi over
longer HDMI. You can't use HDMI camera, HDMI is used merely as wire signal extension for CSI.

https://www.arducam.com/product/arducam-csi-hdmi-cable-extension-module-15pin-60mm-fpc-cable-raspberry-pi-camera-specific-pack-2-1-set/

==== Low light vision

Sionyx has some boating oriented solutions:
https://www.sionyx.com/pages/boating

Image stabilization for boat movements is an important factor too.

==== MotionEye

By default, motioneye service installed and enabled. To disable:

[source, shell]
----
sudo systemctl disable motioneye
sudo systemctl stop motioneye
sudo systemctl status motioneye
----

Default user: admin

Password is empty.

=== Cruising within Cellular Phone Reception

Adding some OpenWrt LTE/4G router greatly improves your boat connectivity to
the world near shore. You should definitely do it to have internet access from your boat.

The OS image gives you internet applications for:

* Email
* Chat
* FB
* YouTube
* Browser
* On-Line Weather
* On-Line Charts
* Marina Booking
* Sailing Education
* SMS
* and much more

=== Offshore Features

For offshore sailors there are number of features pre-loaded into the OS image

* NavTex
* Inmarsat Fleet (receiving messages)
* Using Iridium as modem
* WeatherFax
* GRIB (could be over SSB)
* WinLink
* SDR / HAM Radio Apps
* AIS
* Weather Routing / Climatology
* Celestial Navigation
* Autopilot (PyPilot)
* Satellite Weather
* Radars (several supported)
* Location Reporting

They do require additional hardware, set up and dedication.

=== Watching Movies

Watching on-line (or listening) prepaid copyrighted content (Netflix, Amazon PrimeVideo, Google, Spotify, etc) in
a web browser as Chromium requires closed-source DRM libraries. On arm32 version of the OS you can install it
from add-ons folder ~/add-ons/ by running:

[source, shell]
----
./widevine-lib-install.sh
----

NOTE: As of moment of writing this procedure doesn't work on arm64. It does work on arm32, and even on
arm32 with 64-bit kernel.

=== How it is Made

For those who are comfortable writing software the scripts to create this image
stored on the image itself (for the reference) in /install_scripts.
The full source code to create the image is available at: <https://github.com/bareboat-necessities/lysmarine_gen>

=== Shutting Down / Rebooting

On the desktop click on the 'Commands' icon. You will see a menu from where
you can perform restart/shutdown, and more.

==== Safe Power-Down

Raspberry pi doesn't have a safe power-off feature. I.e. it doesn't perform OS shutdown before
powering off with a button. There are numerous third-party solutions with raspberry pi hats or
custom cases. Make sure you do not forget to install required software for them per vendor documentation.

=== Customizing Desktop

Desktop can be customized by editing the JavaScript file in /var/www/bbn-launcher.

PyPilot web client looks better in dark skin. Switch to the dark theme if it wasn't done for you automatically.

==== Customizing Applications Menu

Applications menu can be customized by editing gnome-applications.menu in ~/.config/menus.

=== Customizing On First Boot

You can add additional customizations which will be performed on system first boot by
mounting OS image and editing /boot/first-boot.sh script. That script as its name suggests
executes only once on the first boot.

=== Known Issues and Workarounds

See: https://github.com/bareboat-necessities/lysmarine_gen/issues

If GPS is lost in OpenCPN the first thing to try is to restart SignalK. You can do it from touchscreen
via desktop 'Commands' icon.

Do not create data loops with your data flows between OpenCPN, AvNav, SignalK, GPSd, Kplex, PyPilot.

==== Touchscreen

NOTE: The touchscreen issues mentioned below fixed since 2021-09-10 release.

* Some applications (namely OpenCPN and gtk2 based as well as some Qt) sometimes stop responding to touch events.
There is a workaround. With your finger you can toggle maximized mode via window frame icon then you
MOVE the window frame by dragging window header few pixels, and switch back to maximized mode if needed.
This should restore touch events in that app.

* Some gtk3 applications menus (ex: terminal) have issues handling touch events. You can select a menu item
with touch but to perform a click on it you would actually need to perform simulated right click
by holding finger a bit longer and letting it go.

==== Wi-Fi DNS

If you use your devices on LAN or WiFi networks they might get assigned different IP addresses from DHCP servers.
However, DNS servers tend to cache (remember) name to IP address mappings for quite some time.
Thus, you can run into DNS name resolution issues if you do not configure DHCP servers to assign
consistent IP addresses (by MAC address for example) to all your devices.

Another situation which can cause name resolution issues in DNS is when one device configured
to be able to choose multiple Wi-Fi networks to connect to.

=== Add-ons

Check /home/user/add-ons directory. It contains number of scripts for installing many additional programs
which for one or another reason couldn't be a part of the distribution image.


=== Default Ports

See:

[source, shell]
----
sudo netstat -tulpen
----

[source]
----

Proto  Port       Transport            Program/Service
tcp    22         ssh                  sshd Secure Remote Shell
tcp    25         smtp                 exim4 e-mail
tcp    139        netbios              smbd
tcp    445        smb                  smbd
tcp    631        CUPS                 cupsd Printing
tcp    2947       gpsd                 gpsd
tcp    3000       http/WS              SignalK
tcp    4713       pulseaudio           pulseaudio audio
tcp    4997       http                 bbn-desktop
tcp    5000       airplay              shairport-sync music
tcp    5037       adb                  android adb
tcp    5900       vnc                  x11vnc
tcp    6600       mpd                  Mopidy MPD Music
tcp    6680       http                 Mopidy Music
tcp    8080       http                 PyPilot_web
tcp    8082       http                 AvNav Ocharts
tcp    8085       http                 AvNav Updater
tcp    8099       http                 AvNav
tcp    8375       http/json            SignalK Deltas
tcp    8765       http                 motioneye
tcp    10110      NMEA 0183            SignalK
tcp    20220      NMEA 0183            PyPilot
tcp    23322      json                 PyPilot
tcp    34567      NMEA 0183            AvNav NMEA out
tcp    dynamic    spotify              librespot
udp    68         DHCP                 dhclient
udp    137        nmb                  nmbd
udp    138        nmb                  nmbd
udp    323        ntp                  chronyd time service
udp    631        IPP                  CUPS Internet Printing Protocol
udp    5353       service discovery    avahi-daemon, chromium, others (bonjour, zeroconf, mDNS)
udp    10116      NMEA 0183            AvNav, KPlex

----


=== Suggestions

The beauty of Linux is that you can customize it for your needs in infinite ways.
While this distro aimed to strike common need, you will find that number of post-install
customization steps would be required. The key is to script those steps, make them non-interactive,
make the steps requite NO GUI. In that case your set up becomes REPRODUCIBLE in case of new
OS image releases. You can share your post-install scripts, so the system can be improved and even more fine-tuned.

While the system supports touchscreens during set-up phase you would still want to have a regular wired keyboard
and mouse attached to it as there is plenty of activities involved on the shell command line.

You do not have to be a software engineer to install the system. A mechanic, electrician, paralegal professional,
civil engineer, money manager are few examples of people with different backgrounds who were able to
install and set it up for their boats.


=== Hardware

This is not my first build of the boat computer with raspberry pi. A lot of ideas can be taken from my
older (2020 build which was based on OpenPlotter). For up-to-date build I would change few things:

* Instead of expensive Argonaut M7 I would have used
(Model: SL07W, Brand Sihovision, Capacitive Touch Screen 7-inch, (1000 nits), IP65, 1024x600, Cost under $300):
https://www.sihovision.com/industrial-touch-monitor/7-inch-industrial-wide-temperaturer-lcd-monitor-with-remote-control-1.html

* My waterproofing technique would be cheaper and better. Instead of costly connectors at the back of the computer (even if it is below deck)
I would use waterproof glands for exits from the enclosure and pigtail connectors. I would cover the point of connection with heat shrink tubing.

* I would have used some kind of safe power-off solution and SSD instead of just SD card. SSD gives HUGE performance gain.

* I would use this OS image (instead of OpenPlotter image)

* dAISy AIS is better solution than SDR

* Use USB 2.0 hub where USB 3.0 not required

For older hardware solutions (lot of it is still valid) see:

https://bareboat-necessities.github.io/my-bareboat/


=== Printing

Printing from Chromium is a bit inconvenient. You need to choose 'Print' menu, then
scroll down and choose 'More Settings' and select 'Print Using System Dialog' which
will let you to choose a printer.


=== Social Networks and Messaging

BBN OS has several programs to help you stay connected with friends
via social networks and messaging applications via Internet.

=== Location Reporting

SignalK comes with preinstalled plugin for saillogger.com

=== Most useful features for average short cruises

* GPS, OpenCPN off-line charts for your sailing area
* IMU Compass
* Tides / Currents in OpenCPN
* Waypoints, routes in OpenCPN, tracking
* AIS in OpenCPN
* Weather Windy, etc if using LTE internet
* Music players
* Dashboards Wind, Speed, Depth, GPS, Local Sunset, etc
* Barograph
* Autopilot (if equipped)
* Cameras for docking and night light
* Local boat WiFi hotspot and LTE gateway

=== IoT

==== Mosquitto MQTT Server

BBN OS image comes with Mosquitto clients and server preinstalled but disabled. To enable and start it:

. Enable and start Mosquitto server (on default port 1883)
+
[source]
----
sudo systemctl enable mosquitto
sudo systemctl start mosquitto
----

. Subscribe to topics
+
[source]
----
mosquitto_sub -t '#'
----

. Publish from SignalK: Enable MQTT Gateway plugin. Pick 'Send data to remote server' with URL mqtt://localhost.
Add topic (Ex: navigation.headingMagnetic). Restart SignalK and observe the data stream in the subscriber.

==== NodeRed

NodeRed is installed into SignalK. To use NodeRed login into SignalK by visiting
http://localhost:3000 clicking 'login', choosing 'remember me' session and storing the password in a browser.


=== Data Analytics

==== Grafana

BBN OS image comes with grafana preinstalled but disabled. To enable and start it:

. Edit the /etc/grafana/grafana.ini file and change line ';http_port = 3000' to 'http_port = 3080' (to avoid conflict with SignalK)
+
[source]
----
sudo nano /etc/grafana/grafana.ini
----

. Enable and start Grafana server
+
[source]
----
sudo systemctl enable grafana-server
sudo systemctl start grafana-server
----


. Access http://localhost:3080  with user and password 'admin'.

==== InfluxDB

. Enable and start InfluxDB server (on default ports 8086 (client-server), 8088 (RPC))
+
[source]
----
sudo systemctl unmask influxdb.service
sudo systemctl enable influxdb
sudo systemctl start influxdb
----

. Initialize database and connect to it (for example) from SignalK barograph plugin.

Chronograf and Kapasitor also come pre-installed.

=== Power consumption

With Raspberry Pi4 power consumption of your system should be around under 4.5 watts without a monitor.
A monitor depending on it's size and backlight brightness (needed for sunlight readability) can add
another 5 watts or even more. Human brain runs on about 12-25 watts for comparison.

=== Upgrading your System

==== Verified Updates

Fixes verified by the development team can be installed by running:

[source]
----
cd /home/user/add-ons
./hot-fixes-install.sh
----

==== All Other Updates

Your system packages can be upgraded following standard Debian packaging system procedure:

[source]
----
sudo apt update
sudo apt upgrade
----

SignalK server and modules can be upgraded using SignalK App Store.

OpenCPN charts can be updated using OpenCPN chart downloader plugin.

NOTE: As result of software upgrades you might end up with a configuration which wasn't previously tested.
Though you might be able to get some support via community forums at:
https://github.com/bareboat-necessities/lysmarine_gen/discussions

=== Data Flow

.Data Flow
ifdef::env-github[image::bbn-os-data-flow.svg[Data Flow]]
ifndef::env-github[]

[plantuml,bbn-os-data-flow,svg]
....
!include plantuml/bbn-os-data-flow.puml
....

endif::[]

{zwsp} +
{zwsp} +

== Supported Hardware

=== Monitors

For a cabin monitor many people do not use special marine grade ones.
If you have enough space on your nav station desk for a keyboard and a mouse,
you might consider getting a screen without touch functionality.

For a cockpit display you need >1000 nit brightness for sunlight readability,
waterproof, touchscreen, with backlight (brightness) control buttons for
night sailing. You would need long HDMI and USB (for touch) cables to
connect to raspberry pi below deck. There are even fiberoptic solutions for that. They
allow thinner cables.
Bonus, if your touchscreen display comes
with built in speakers for alarms. Check Sihovision product line, if one of
their products will suit you.


=== IMU, compass, accelerometer, gyroscope

PyPilot supports these via RTIMULib2. Here is a list of supported units by RTIMULib2:

- InvenSense MPU-9150
- InvenSense MPU-9250
- InvenSense MPU-9255
- STM LSM6DS33/LIS3MDL
- STM L3GD20H/LSM303D
- STM L3GD20/LSM303DLHC
- STM LSM9DS0
- STM LSM9DS1
- STM LSM6DSL
- InvenSense ICM-20948
- Honeywell HMC5883L with ADXL345 and L3G4200D
- STM ISM330DHCX
- Bosch BMX055 (experimental magnetometer support)
- Bosch BNO055 (doesn't work reliably on Pi, clock issues)

PyPilot Documentation recommends using 9 Dof (9 Degrees of freedom) IMU with mpu9255.

Even without autopilot motor controller these sensors allow displaying roll, pitch, and yaw.

=== Environmental Sensors

==== Barometer, Temperature, Humidity I2C Sensors

These are handled by Signal-K plugins. Supported ones are:

- Bosch BME280
- Bosch BME680

There is also barograph plugin in SignalK.

=== AIS

There are several options:

- If you have AIS transducer you just use it via NMEA bus.
- AIS built in into NMEA multiplexer used via NMEA network
- dAISy USB AIS or Raspberry Pi dAISy AIS Hat. USB one is easier to set up.
- Decode AIS radio signals using SDR. Probably the worst option as SDR is quite
energy consuming for that task to be run constantly.

=== Radars

OpenCPN Radar plugin reports support of the following radars:

- Navico/B&G/Lowrance/Simrad: BR24, 3G, 4G, and HALO20, 20+, 24, 4, 6, and 8
- Garmin: HD and xHD
- Raymarine: Ethernet-Analog: RD218, RD418 / Ethernet-Digital: RD418D, RD424D

Quantum/Quantum2 Radars from Raymarine seems are not supported by OpenCPN,
nor are the Garmin Fantom radars, or Furuno units.

We didn't have hardware to all these. So reports of successful installations
and encountered issues are welcome.

=== USB Hubs

Choose powered USB hub which doesn't backfeed power into pi4, to avoid issue of pi4 not being able to reboot
when USB hub is still 'on'.

If you do not plan to connect to your USB hub storage devices, cameras, network cards (high speed devices),
then USB 2.0 hub will do the job. No need for USB 3.0 hub.

USB ports follow color convention:

[cols="1,1"]
|===
|Type |Color

|USB 1.0
|[white black-background]#*White*#

|USB 2.0
|[black]#*Black*#

|USB 3.0
|[blue]#*Blue*#

|USB 3.1
|[teal]#*Teal*#

.3+|Charge & Sleep or High Current
|[yellow]#*Yellow*#

|[maroon]#*Red*#

|[red]#*Orange*#

|===
=== LTE/Wi-Fi Routers

Wi-Fi router you need is somewhat different from your home router. Your home router connects
wired to Internet WAN and it gives you local Wi-Fi. On a boat situation reverses. Your WAN is
marina's Wi-Fi and your Pi should (preferably) be wired into the router. These
Wi-Fi routers are being sold as Travel Wi-Fi routers.
Not all cheap Wi-Fi routers will give you ability to connect to marina Wi-Fi and share it on a boat.
It's better to choose the ones running OpenWrt operating system, which is Unix based and open-source.
LTE is a very valuable feature.

Few recommended would be: GL.iNet (GL-X750 V2) Spitz router, Teltonika RUTX12 (dual SIM).

=== SD Cards

In SD card you will be looking at speed (i/o reads, i/o writes), durability, size.
>32Gb is recommended.

=== SeaTalk1

SeaTalk1 is Raymarine proprietary protocol. Many popular Autohelm Raymarine autopilots use it.
To integrate it into your system you have a number of choices:

- Use bi-directional NMEA 0183 multiplexer which supports one SeaTalk1 port. First
vendors to check are YakBitz and Quark-elec Marine. There are others as well. You want
bi-directional multiplexer to be able to control autopilot from your pi via NMEA.
There is a dedicated Autohelm autopilot plugin in SignalK.

- Buy a dedicated Seatalk1 to NMEA converter.

- For read/only Seatalk1 connection you can use this solution:
https://github.com/SignalK/signalk-server/blob/master/Seatalk(GPIO).md

SeaTalk1 was reverse engineered and converter into NMEA is available:
https://github.com/MatsA/seatalk1-to-NMEA0183
https://github.com/Thomas-GeDaD/Seatalk1-Raspi-reader

=== NMEA 0183

Widely supported. Many options to connect to pi.

USB/Serial:

- with FTDI FT232 chipset https://www.amazon.com/dp/B07B416CPK
- with CP210x chipset RS-485 to USB converter
- with CH340 chipset RS-485 to USB converter
- with Prolific PL2303 chipset RS-485 to USB converter
- NMEA 0183 Multiplexers working over USB (YakBitz, Quark-elec, etc)

NOTE: FTDI is preferable choice between FTDI, CP210x, CH340, or PL2303.
FTDI seems always have unique serial ID which might be missing on others, and
it will make harder to write udev rules to uniquely name the device on USB bus.

Board:

- PiCAN-M Raspberry Pi Hat by https://www.skpang.co.uk
- Sailor Hat for Raspberry Pi by https://hatlabs.fi
- GeDaD MCS, Marine Control Server Board by https://www.gedad.de/

TCP/IP:

- NMEA 0183 Multiplexers working over WiFi or Ethernet


=== NMEA 2000

NMEA 2000 protocol was reverse engineered as a part of this project: https://github.com/canboat/canboat

Since then NMEA 2000 had been natively incorporated into SignalK as well.

Options to connect Pi to NMEA 2000 bus:

PCB boards/hats:

- PiCAN-M Raspberry Pi Hat by https://www.skpang.co.uk
- Sailor Hat for Raspberry Pi by https://hatlabs.fi
- GeDaD MCS, Marine Control Server Board by https://www.gedad.de/

USB/Serial:

- Actisense NGT-1 NMEA 2000® to PC https://actisense.com/products/ngt-1-nmea-2000-to-pc-interface/
- CANable and CANable Pro by https://canable.io/
- iKonvert NMEA 2000-USB Converter
- ShipModul MiniPlex-3USB-N2K
- Yacht Devices NMEA 2000 USB Gateway YDNU-02

TCP/IP gateways:

- Bi-directional NMEA 2000 Multiplexer WiFi (Quark-elec, etc)
- ShipModul MiniPlex-3E-N2K
- Yacht Devices NMEA 2000 Ethernet Gateway YDWG-02
- Yacht Devices NMEA 2000 USB Gateway YDEN-02
- NavLink2 digitalyachtamerica.com

OpenCPN TwoCan plugin has a list of compatible with it devices too.

Stay away from devices which just convert NMEA 2000 into NMEA 0183.
You need to feed NMEA 2000 into SignalK and be able to receive it too.

=== GPS

Several options to connect:

USB:

- Many USB "mouse" GPS should work on BBN OS after plugging-in and giving them some time
to acquire satellites outside of the house. Cold start can take half an hour or so with some GPS models.

Re-use GPS built-in into LTE router:

- LTE modems on LTE routers have built-in GPS. If you followed our advice on using a router with
OpenWrt OS then you will be able to install KPlex (or gpsd) on it and set up a connection to it
from SignalK (or/and OpenCPN, AvNav) running on your raspberry pi.

NMEA:

- Use GPS from your NMEA network. VHF have GPS and NMEA interfaces. Some NMEA multiplexers come with GPS built-in
as well as most chartplotters.

PCB Boards connected to Pi:

- Example BerryGPS. Disadvantage of those is that they use your Pi's built-in UART and you might have other
devices that you want to use it instead.


=== SDR

RTL-SDR, SDRPlay SDR, HackRF SDR, LimeSDR, and likely others

Interfaces USB, Ethernet

SDRs consume quite some power. So it's better to connect them to pi via a powered USB Hub (in case of USB interface).

=== SSD

Raspberry Pi OS supports NVMe and SATA SSDs with an appropriate extension board, or a Pi case, and
their vendor's driver.

NVMe apparently doesn't give much performance boost over SATA for pi4 with
an exception to CM4 (Pi4 Compute Module) performing better on writes with NVMe drives.
pi4 internal interface is the bottleneck for transfer rate speed.

Booting from NVMe drives got supported by linux kernel on pi4 just recently (some bugs might remain).

Perform a benchmark of your SSD after installation with correct drivers. Make sure it falls
into expected range.

USB stick drives (flash drives) do not perform as well as NVMe and SATA SSDs.

=== NavTex

- NASA Marine PC Navtex USB with an antenna (BBN OS comes with a program called PC-NavTex for it). ~$220
- USB Devices from wetterinfobox.com (WIB2 - NAVTEX for PC) http://www.wetterinfobox.com

=== RTC (Real Time Clock)

Raspberry pi doesn't have clock module to keep the time when it's off, so you might
consider adding one.

There are vew common i2c RTC modules:

- DS3231 RTC
- DS1307 RTC

Make sure there are no conflicts in addresses with your other i2c devices. Other
devices usually have at least one option for switching to another address to avoid conflicts.

=== Sound Cards

As Raspberry Pi doesn't have audio input, for use with SSB radio you might want to have an additional
sound card which has both audio in and out. There is good selection of options, but check reviews
and compatibility with raspberry pi4.

=== Cameras

=== IP Cameras

IP Cameras should work with MotionEye using their rtsp:// URLs.

=== CSI connected cameras

We need your help with testing it.

=== USB connected cameras

We need your help with testing it.

=== 1-Wire

SignalK Raspberry Pi 1wire plugin supports connecting multiple DS18B20
1-wire temperature sensors.

=== Power, 12v -> 5v Converters

This converter was used with no issues:

TOBSUN EA50-5V DC 12V 24V to DC 5V 10A 50W Converter Regulator 5V 50W Power Supply Step Down Module Transformer

    Over-voltage, over-current, over-temperature, short-circuit auto protection

    Input voltage: 12/24V, Output: 5V/10A

https://www.amazon.com/dp/B01M03288J

{zwsp} +

As well as this UBEC:

US Ship Hobbywing 5V/6V 3A Switch-mode UBEC, Max 5A Lowest RF

https://www.amazon.com/dp/B008ZNWOYY

Avoid powering Pi4 via GPIO pins directly as it bypassed overvoltage self healing fuse
built-in into pi.

==== Power Management, Victron, Venus OS

SignalK has good support for interfacing with Victron Energy products and their Venus OS.

SignalK comes with:

- Victron Venus OS Plugin
- ModBus Client Plugin

=== Antennas

There is a great variety of antennas of a boat. Directional vs omnidirectional,
active vs passive, internal (some are just a part of a circuit on a PCB) vs external,
grounded vs ungrounded, receiving-only vs receiving/transmitting, and a wide variety of shapes.

==== VHF, AIS

VHF and AIS use similar frequencies, need be in direct line of sight, so the higher they are the better range.
They are limited by Earth curvature. Range is around 30 miles. They can use the same antenna with a proper splitter.
Transmitter device on AIS has to be licensed and registered.

==== Wi-Fi, LTE/4G

Similar but distinct separate antennas. Can work even if inside cabin of a fiberglass boat. Range varies on antenna
gain. Wi-Fi usually in hundreds of feet. LTE/4G in/under few miles. LTE/4G uses cellular network of antennas
of network providers which covers most populated areas.

==== GPS

Receive-only. Doesn't need to be high. Needs a clear sky view of multiple satellites. External ones are usually
active and placed inside of a mushroom-looking plastic.
Designed to have almost world-wide coverage (except of extreme North/South poles areas).
There are several GNSS systems with different satellite constellations.
GPS (US), BEIDOU (China), GALILEO (EU), GLONASS (Russia), and QZSS (Japan)

==== Iridium, StarLink

Both are satellite communications. Iridium designed for a hand held phone with a small antenna.
StarLink is communicating with more satellites on much lower orbits, and it is designed for a directional
pizza-sized dish antenna, automatically orienting itself using a motor.
Designed to have almost world-wide coverage (except of extreme North/South poles areas).

==== FM (Frequency Modulation)

Short piece of wire, small telescoping antenna. Receive only. 30-40 miles range.
Transmitted from ground stations. VHF is FM too, but FM is loosely used term for music and local news broadcast
channels.

==== Bluetooth, 433MHz FM RF

Bluetooth antennas are small and often just a part of a PCB circuit.
Bluetooth range is really short and it is about 10 meters.

433MHz FM RF range is about 300 meters. Often used for remote controls. Wireless masthead wind transducers, etc.

==== NavTex, WeatherFax

Receive only. Transmitted from ground stations with predefined intervals of time.
WeatherFax frequency depends on the region. You need to know a schedule of WeatherFax transmitting stations
for different areas.

NavTex frequency is 518 kHz in the medium frequency band. 490 kHz in addition in some countries.
Both NavTex and WeatherFax designed for almost world-wide coverage and offshore sailing.

PA0RDT active mini-whip antenna is good for NavTex and WeatherFax frequencies
http://dl1dbc.net/SAQ/miniwhip.html

==== SSB, HAM

Transmitting on SSB (Single Side Band) radio requires a license for an operator except of in an emergency.
Designed for long range communications at sea and for offshore vessels. An insulated backstay of a mast can
serve as SSB antenna. Propagation of SSB radio waves work on reflected or
refracted back toward Earth from the ionosphere. Performance ranges in excess of 4000 miles.
Some parts of SSB frequency spectrum work better at night, others during daytime.

HAM (aka amateur) radio also requires a license for an operator to transmit.

==== LoRa

LoRa (Long Range) radio is license-free for both transmitting and receiving.
Range 2-5 km in open. Used as a low power (and low traffic bandwidth) wireless platform for Internet of Things (IoT).
LoRa antennas are small and usually attached to its devices.

== How you can help

. Add a star on our github project page https://github.com/bareboat-necessities/lysmarine_gen
. Report a bug (or contribute to resolving an existing issue) https://github.com/bareboat-necessities/lysmarine_gen/issues
. Spread the word. There are many sailing forums on Internet and Facebook. Let other people know what BBN OS could do for you.
. Respond to a question in our discussion forums: https://github.com/bareboat-necessities/lysmarine_gen/discussions
. Post a video on YouTube explaining how you use BBN OS on your boat
. Submit a github pull request with code changes to improve BBN OS
. Post a blog article or contribute to HOWTOs section of this document.
. Of course, the BBN OS is completely open-source and free to use.

== HOWTOs

Please send us your HowTo, and we can add it here for everyone to find. Thanks

=== BerryGPS-IMU V3

- Install the BerryGPS-IMU V3 hat
- Follow steps to enable i2c and disable serial port https://ozzmaker.com/berrygps-setup-guide-raspberry-pi/
- Remove serial console mentioned in /boot/cmdline.txt (argument with serial0 and baud rate)
- Reboot
- sudo i2cdetect -y 1 (should show you addresses)
- Create pypilot connection to signalK (see https://bareboat-necessities.github.io/my-bareboat/bareboat-os.html#_imu )
- Set up barometer feed from SignalK ( https://bareboat-necessities.github.io/my-bareboat/bareboat-os.html#_barometer_temperature_humidity )
- IMU data heading etc should come from pypilot NMEA
- check it with telnet localhost 20220

Brief explanation:

- i2c should be enabled, serial console disabled in config.txt
- i2c driver should be loaded at boot (that's what raspi-config step does)
- At this point you should have data readable from GPS (via /dev/serial0) and IMU / barometer (via i2c)
- Now you set up routing of this data into dashboards, chartplotters
- IMU is read by pypilot, which feeds it via 20220 tcp port using NMEA 0183 format
- pypilot also needs to have connection via SignalK web socket to port 3000 of signalK
- That connection needs to be authorized made READ/WRITE in signalK using their token exchange procedure
- GPS is read by signalK by creating NMEA connection to /dev/serial0 port (set correct baud rate)
- Barometric/temp data is read by SignalK using signalK BME280 plugin. Make sure setting polling interval below 30 seconds (because OpenCPN expires non-navigational data every 30 seconds)
- Calibrate level IMU on water. Calibrate your IMU compass, using pyPilot calibration utility.
- I use external GPS antenna with it. (It needs to be an active antenna). There is a jumper/or switch on the Berry board to choose external antenna

NOTE: Cellular, GPS, WiFi Antenna (3 in one), Model AFCJF3, Price $80
Designed for marine and recreational vehicles (RV), this multi-band
Cellular, GPS, WiFi Antenna (696 MHz - 5900 MHz / 5.9 GHz) is a 3-way omni-directional,
IP67 waterproof antenna for harsh environment communication applications.
https://www.signalbooster.com/products/cellular-gps-wifi-antenna

Check with commands:

 sudo i2cdetect -y 1

should show addresses on the bus, then

 systemctl status pypilot@pypilot

should show that pypilot service as enabled, running and has no errors.

 telnet localhost 20220

should show stream of heading NMEA data from pypilot.

 telnet localhost 10110

should show both GPS and heading NMEA sentences from SignalK.

Also, check this FAQ for common berryGPS issues:

https://ozzmaker.com/berrygps_imu-faq/

disabling echo on serial port might be required, as well as enabling ZDA NMEA time sentence.

ublox GPS receivers have extensive configuration. Check: https://gpsd.io/ubxtool-examples.html

=== RTL8812AU drivers

Following these steps it compiled fine from the first attempt https://github.com/aircrack-ng/rtl8812au

There is also a script to install various additional WiFi cards drivers

[source, shell]
----
cd /home/user/add-ons
./wifi-drivers-install.sh
----

=== Cloud Storage

Using rclone you can store and sync your files on many cloud vendors storage.
More: https://github.com/rclone/rclone

[#phone_gps]
=== Using your smartphone as NMEA GPS receiver

Install GPS2IP application on your smartphone. Start it and enable GPS2IP in it.
Your phone should be on the same local network as your boat computer.
In SignalK add gps2ip_on_smartphone NMEA TCP connection to the IP address 
shown in GPS2IP app and the port specified there (usually 11123).

=== How to navigate with your smartphone as GPS receiver and have an Internet access on a boat within cellular reception

If you have a smartphone on board then you can use it as a source of NMEA GPS data and Internet provider
for all your boat devices connected to your boat computer.

* Follow steps <<tether>> (or <<tether_android>>) to connect to your phone and use it as an Internet hotspot.

* Follow steps <<phone_gps>> to use your phone GPS as NMEA 0183 source of GPS data.

=== Autostart programs on desktop startup

You can set up which programs you want to autostart when desktop comes up in
Administration->Budgie Desktop Settings. Many users would probably want OpenCPN and KIP Dashboard
right away.
