= Estimating wave height from IMU accelerometer on a moving boat (Early Draft)
mgrouch <mgrouch@users.noreply.github.com>
{docdate}, Wave Height from IMU accelerometer
:imagesdir: images
:doctype: book
:organization: Bareboat Necessities
:description: Bareboat Necessities, Wave Height from IMU accelerometer
:title-logo-image: image:bareboat-necessities-logo.svg[Bareboat Necessities Logo]
ifdef::backend-pdf[]
:source-highlighter: rouge
:toc-placement!: manual
:pdf-page-size: Letter
:plantumlconfig: plantuml.cfg
endif::[]
ifndef::backend-pdf[]
:toc-placement: manual
endif::[]
:stem:
:experimental:
:reproducible:
:toclevels: 4
:sectnums:
:sectnumlevels: 3
:encoding: utf-8
:lang: en
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:env-github:

{zwsp} +

ifndef::backend-pdf[]

image::bareboat-necessities-logo.svg[Bareboat Necessities Logo]

{zwsp} +

== Abstract

Usual methods for measuring elevation built-in into modern smartwatches and smart devices are based on fusion of data
(using Kalman filters, etc) from IMU (accelerometer) and barometer sensors. These methods are designed to measure steps up and down stairs,
hiking activities, and so on. However, using pressure as a useful source of elevation data is not suitable to measure
the wave height from a boat. The surface of the wave itself (at least in trochoidal wave model) is the surface of
equal pressure. Real waves are more complicated but nevertheless measuring air pressure on their surface
to estimate amplitude of the wave would lead to measuring mostly noise.

Calculating elevation (displacement) using double integration of the acceleration leads
to huge result drift due to not knowing initial displacement, initial vertical velocity
and due to signal noise and accelerometer bias.

This article describes two different methods to estimate wave height, frequency, period
from a moving boat using IMU (accelerometer) and other common boat sensors such as anemometer (wind), GPS, and compass.
One method is based on Kalman method which calculates second integral of acceleration with a drift correction
based on the fact that in wave average displacement equals to zero. Another method doesn't use
integration at all. Instead, it measures max/min acceleration and assumes wave shape to be trochoidal.
Based on max/min acceleration and observed wave frequency (later adjusted using Doppler effect formulas)
the method recreates parameters of the trochoid wave allowing it to estimate the wave height.

Initial velocity and position for Kalman filter are taken as estimates from trochoidal model to
allow Kalman filter to converge faster.

== Trochoidal Waves

Gravitational {nbsp} stem:[g] {nbsp} (m/s^2): {nbsp}{nbsp}{nbsp}
stem:[g = 9.81]

Rotation center of trochoidal wave particle in Z axis (always negative) (m): {nbsp}{nbsp}{nbsp}
stem:[b]

Wavelength (m): {nbsp}{nbsp}{nbsp}
stem:[L]

Wave equation:

stem:[X(t) = H sin(k c t)]

stem:[Z(t) = - H cos(k c t)]

Wavenumber (1/m): {nbsp}{nbsp}{nbsp}
stem:[k = (2 pi) / L]

Wave amplitude (m):  {nbsp}{nbsp}{nbsp}
stem:[H = e ^(k b) / k = L / (2 pi) e ^ ((2 pi b) / L)  ] {nbsp}{nbsp}{nbsp} => {nbsp}{nbsp}{nbsp}
stem:[b = ln(H k) / k = L / (2 pi) ln ((2 pi H) / L)  ]

max(H) amplitude (m):   {nbsp}{nbsp}{nbsp}  stem:[H_max = L / (2 pi)] {nbsp}{nbsp}{nbsp} when {nbsp} b = 0

Depth (m): {nbsp}{nbsp}{nbsp}
stem:[d]

Wave speed (m/s): {nbsp}{nbsp}{nbsp}
stem:[c = sqrt(g / k tanh(k d))] {nbsp},{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}
for deep water waves: stem:[c = sqrt(g / k) = sqrt((g L) / (2 pi))],  {nbsp}{nbsp} stem:[L = (g T ^ 2) / (2 pi)]

Wave period (s):   {nbsp}{nbsp}{nbsp}
stem:[T = L / c]

Wave frequency (Hz=1/s):   {nbsp}{nbsp}{nbsp}
stem:[f = 1 / T = c / L]

Vertical motion is harmonic.

Vertical displacement:
stem:[Z(t) = - H cos(k c t) = - L / (2 pi) (a(t))/g]

Vertical velocity:
stem:[u(t) = Z^'(t) = k c H sin(k c t) = c e ^ ((2 pi b) / L) sin(k c t)]

stem:[u_max = c e ^ ((2 pi b) / L)]

stem:[u_max(b=0) = c]

Vertical acceleration:
stem:[a(t) = u^'(t) = k^2 c^2 H cos(k c t) = g e ^ ((2 pi b) / L) cos(k c t)]

stem:[a_max = -a_min = k^2 c^2 H =  ((2 pi) / L) ^ 2 ((g L) / (2 pi)) L / (2 pi) e^((2 pi b)/L) = g e^((2 pi b)/L)  ]

stem:[b = L / (2 pi) ln(a_max / g)]

Slope stem:[s(t)]:

stem:[x_b(t) = X(t) - t Delta v]

stem:[s(t) = d/ (dx_b) ((Z(t)) / (x_b(t))) =  (d/dt(Z)) / (d/dt(x_b)) = (d/dt(- H cos(kct))) / (d/dt(H sin(kct) - t Delta v)) = (cHk sin(kct)) / (cHk cos(kct) - Delta v)]


=== Doppler effect

stem:[f] {nbsp} is emitted frequency (Hz=1/s),

stem:[f_o] {nbsp} is observed frequency (Hz=1/s):

stem:[c] {nbsp} is the propagation speed of waves in the medium

stem:[Delta v] {nbsp} is the opposite of the velocity of the receiver
relative to the source: it is positive when the source and the receiver are moving towards each other.

stem:[f_o = (c +- Delta v) / c f]

stem:[L] {nbsp} is source wavelength (m) for trochoidal wave.

For trochoidal wave:

stem:[f = c / L] {nbsp} => {nbsp} stem:[f_o = (c +- Delta v) / L ],

stem:[c = sqrt((g L) / (2 pi))] {nbsp} => {nbsp} stem:[f_0 = (sqrt((g L) / (2 pi)) +- Delta v) / L]

stem:[L = (sign(Delta v) sqrt(8 pi f_o g  Delta v + g ^ 2) + 4 pi f_o  Delta v + g) / (4 pi f_o ^ 2)]

Apparent (observed) vertical acceleration:

stem:[a_(observed)(Delta v, t) = d^2/dt^2 (- H cos(k (c + Delta v) t)) = H k^2 (c^2 + 2 c Delta v + (Delta v)^2) cos(k (c + Delta v) t)]

stem:[a_(observed_max) = H k^2 (c^2 + 2 c Delta v + (Delta v)^2)] =>

stem:[H = H(L, Delta v) = a_(observed_max) / (k^2 (c^2 + 2 c Delta v + (Delta v)^2)) ]

stem:[a_max = a_(observed_max) c^2 / (c^2 + 2 c Delta v + (Delta v)^2)]

== Trigonometry of a boat movement

=== Terminology

_AWS_ {nbsp} is Apparent Wind Speed (relative to the boat heading)

_AWA_ {nbsp} is Apparent Wind Angle (relative to the bow heading, 0 to 180, starboard plus, port minus)

_AWD_ {nbsp} is Apparent Wind Direction (relative to true north)

_AGWS_ {nbsp} is Apparent Ground Wind Speed (relative to the boat course over the ground)

_AGWA_ {nbsp} is Apparent Ground Wind Angle (relative to the boat course over the ground, 0 to 180, starboard plus, port minus)

_AGWD_ {nbsp} is Apparent Ground Wind Direction (relative to true north)

_SPD_ {nbsp} is Knotmeter speed (relative to the water)

_HDT_ {nbsp} is Heading true (relative to true north)

_HDM_ {nbsp} is  Heading magnetic (relative to magnetic north)

_DFT_ {nbsp} is  Current Drift (speed of current, relative to fixed earth)

_SET_ {nbsp} is  Current Set (direction current flows toward relative to fixed earth true north)

_SOG_ {nbsp} is  Speed Over Ground (relative to the fixed earth)

_COGT_ {nbsp} is Course Over Ground true (relative to the fixed earth true north)

_COGM_ {nbsp} is Course Over Ground magnetic (relative to the fixed earth magnetic north)

_GWS_ {nbsp} is Ground Wind Speed (relative to the fixed earth)

_GWD_ {nbsp} is Ground Wind Direction (relative to true north)

_TWA_ {nbsp} is True Wind Angle (relative to the heading, 0 = upwind, 180deg = downwind, (+ starboard, - port))

_TWS_ {nbsp} is True Wind Speed (relative to the water)

_TWD_ {nbsp} is True Wind Direction (relative to true north)

_POS_ {nbsp} is position LAT, LON (latitude, longitude)

_TB(POS1, POS2)_ {nbsp} is Bearing true (true north angle to maintain in course to reach from POS1 to POS2)

=== Calculating true wind and speed through water based on difference in heading and course over ground

Having both true heading and true course over the ground allows calculating true wind vector parameters and
speed through the water (SPD):

stem:[SPD = ((dist(POS2, POS1)) / (t_\text{end} - t_\text{start}) - DFT * cos(COGT - SET)) * cos(COGT - avg(HDT))]

stem:[TWS = sqrt((avg(AWS)) ^ 2 + SPD ^ 2 - 2 * avg(AWS) * SPD * cos(avg(AWA)))]

stem:[TWA = +- arccos((avg(AWS) * cos(avg(AWA)) - SPD) / (TWS))]

For Doppler effect formulas:

stem:[Delta v = SPD * cos(TWA)]

=== Heading True from Magnetic

IMU helps measuring magnetic heading HDM. To calculate true heading, it is required to have
Earth magnetic model and using location and time it gives you magnetic variation.

[source, python]
----
import wmm2020

yeardec = datetime.date.today().year
alt_km = 0
declination = wmm2020.wmm(glat, glon, alt_km, yeardec).decl

----

=== Leeway

Although leeway calculation is not required for the algorithm (it gets taken into account with using
heading to course over ground difference), for completeness, here is the popular empirical formula:

Leeway (deg) is angle to adjust heading to maintain constant COG (assuming no current)

stem:[\l\eeway = heel  K / (SPD ^ 2)]

stem:[heel] {nbsp}{nbsp} is boat heel and needs to be in (degrees) for the formula above

stem:[SPD]  {nbsp}is speed through water  and needs to be in (kt)

stem:[K] {nbsp}{nbsp}{nbsp}{nbsp}{nbsp} is boat and boat load specific constant (kt^2), about 10.0


== IMU

=== Getting vertical acceleration from IMU

Most IMU libraries provide a way to get the attitude quaternion stem:[q].
Using this quaternion to get acceleration in Earth XYZ from IMU frame xyz: stem:[\text{accel} = (a_x, a_y, a_z)] vector,
the quaternion stem:[q] is used to rotate vector stem:[\text{accel}]

stem:[\text{accel}_\text{earthXYZ} = q * \text{accel} * q']

where stem:[q'] is inverted quaternion stem:[q].

The same quaternion can be used to get Euler angles of pitch, roll and yaw.
Yaw would correspond to the magnetic heading.

NOTE: To estimate max acceleration it's not needed to extract vertical part of acceleration.
Just magnitude of acceleration stem:[a=sqrt(a_x^2 + a_y^2 + a_z^2)] should be sufficient.

=== AHRS (attitude and heading reference system) fusion algorithms

If quaternion from IMU is not available, then it can be calculated using AHRS fusion algorithms:

* Madgwick algorithm
* Mahony algorithm
* RTQF quaternion fusion for lower power processors
* Extended Kalman Filter (EKF)

== Kalman filter to double integrate vertical acceleration into displacement without integration drift

Ref:

Sharkh S. M., Hendijanizadeh2 M., Moshrefi-Torbati3 M., Abusara M. A.:
A Novel Kalman Filter Based Technique for
Calculating the Time History of Vertical
Displacement of a Boat from Measured
Acceleration,
Marine Engineering Frontiers (MEF) Volume 2, 2014

The method uses assumption that average vertical displacement is zero. So it takes third integral of acceleration
as input measurement with zero value. Vertical acceleration on each step is the value used in transition offset.

So only input observation value is 0 (third integral of acceleration).
Acceleration used in transition offset needs to exclude Earth gravitational g and accelerometer bias.
So avg(acceleration) is subtracted from it.

Accelerometer noise will make the filter to converge slower.
Accelerometer bias will skew the displacement on one side.
Giving too low covariances will flatten the result too much. Too high covariances will make it jump too much.

Low pass filter is needed to get rid of high frequency noise before running this filter to get better results.

Kalman method parameters.


Transition matrix:

stem:[ F = [[1, dt, 1/2 dt ^ 2 \], [0,  1,       dt\], [0,  0,        1\]\]  ]


Transition offset:

stem:[ B = ( (1/6 dt^3), (1/2 dt^2), (dt) ) ]


Observation matrix:

stem:[ H = (1, 0, 0) ]


Transition covariance:

stem:[ Q = [[ \text{PosIntegral_Trans_Variance}, 0, 0 \], [0, \text{Pos_Trans_Variance}, 0 \], [0, 0, \text{Vel_Trans_Variance} \]\] ]


Observation covariance:

stem:[ R = [[ \text{PosIntegral_Variance} \]\] ]


Initial state mean (height integral, height, velocity):

stem:[ X0 = ((0), (\text{height_from_trochoid_model}), (\text{velocity_from_trochoid_model})) ]

Initial state covariance:

stem:[ P0 = [[ \text{PosIntegral_Variance}, 0, 0\], [0, 1, 0\], [0, 0, 1\]\] ]

[source, python]
----
from pykalman import KalmanFilter
import numpy as np

kf = KalmanFilter(transition_matrices=F,
                  observation_matrices=H,
                  transition_covariance=Q,
                  observation_covariance=R,
                  initial_state_mean=X0,
                  initial_state_covariance=P0)

for t in range(n_timesteps):
    if t == 0:
        filtered_state_means[t] = X0
        filtered_state_covariances[t] = P0
    else:
        observation = 0
        transition_offset = B * (accZ_val[t] - acc_avg)
        filtered_state_means[t], filtered_state_covariances[t] = (
            kf.filter_update(
                filtered_state_mean = filtered_state_means[t-1],
                filtered_state_covariance = filtered_state_covariances[t-1],
                transition_offset = transition_offset,
                observation = observation
            )
        )
----

The wave height needs to be evaluated based on the results on the end side of the sampling interval.
The results in the beginning of the sample interval will have extra spikes due to Kalman
filter taking time to converge (without knowing initial velocity and position and adjusting
covariances).


=== FFT to calculate observed frequency of waves

Fast (discrete) Fourier Transform (FFT) is used to find main frequency (the one which carries most energy) of the waves.

[source, python]
----
import numpy as np
from scipy import fft

SAMPLE_RATE = 1.0 / dt
N_SAMP = n_timesteps

w = fft.rfft(accZ_val)
freqs = fft.rfftfreq(N_SAMP, 1 / SAMPLE_RATE)

# Find the peak in the coefficients
idx = np.argmax(np.divide(np.divide(np.abs(w), freqs), freqs))
freq = freqs[idx]
freq_in_hertz = abs(freq)
period = 1 / freq_in_hertz
----


=== Butterworth Low Pass filter

Butterworth Low pass filter is used to filter out high frequencies noise in input
to Kalman filter

[source, python]
----
import numpy as np
from scipy import signal

sos = signal.butter(2, freq_in_hertz * 8, 'low', fs=SAMPLE_RATE, output='sos')
low_pass_filtered = signal.sosfilt(sos, accZ_val)
----

=== Aranovskiy on-line frequency estimator

Instead of FFT method for finding main wave frequency we could use Aranovskiy frequency estimator which is
a simple on-line filter.

Ref:

Alexey A. Bobtsov, Nikolay A. Nikolaev, Olga V. Slita, Alexander S. Borgul, Stanislav V. Aranovskiy

The New Algorithm of Sinusoidal Signal Frequency Estimation.

11th IFAC International Workshop on
Adaptation and Learning in Control and Signal Processing
July 3-5, 2013. Caen, France

https://www.sciencedirect.com/science/article/pii/S1474667016329421[The New Algorithm of Sinusoidal Signal Frequency Estimation]



== Measuring wave height from a moving boat


=== Measurable input parameters

Open sea waves have periods 20 sec or even longer. So sample duration time
should be in minutes to capture several waves. Playing with reference data without noise
shows described Kalman algorithm needs about 10 wavelength to converge accurately.
So with longer way samples needs to be longer. 5-15 mins.

Acceleration positive => position negative. They are in counter phase. This could allow setting initial position for Kalman filter better.

Pitch negative => speed vector is pointing down. This could also allow setting initial velocity for Kalman filter better.

So for initial position and speed in Kalman filter:

stem:[pos_\text{init} = - a_\text{init} / (k^2 c^2) = - a_\text{init} / (g k) = - L a_\text{init} / (2 pi g) ]

stem:[tan(\p\i\tch_\text{init}) = const_1 * s_\text{init}(Delta v = 0)] {nbsp}{nbsp} tangent of pitch is proportional to wave slope

stem:[vel_\text{init} =  kcH cos(kct) * s_\text{init}(Delta v = 0) = (kcH) / (const_1) sin(\p\itch_\text{init}) = const_2 * c * sin(\p\itch_\text{init}) ],

stem:[const_2] to be found empirically (it's vessel specific too).

Or

stem:[vel_\text{init} = c e^((2 pi b)/L) sin (arccos (a_\text{init} / g e^(-(2 pi b)/ L))) * sign(\p\itch_\text{init}) ]


* t_start, t_end - time interval of measurements (about 5 mins)
* POS(t) as LAT(t), LON(t)
* AWA(t) AWS(t)
* COG(t) SOG(t)
* HDM(t) + mag_variation -> HDT(t)
* DFT(t) SET(t) - (possibly from current/tide stations harmonics data)
* heel(t), pitch(t)
* SPD(t) - possibly (might be missing) => leeway(heel(t), SPD(t))
* accel(t, x, y, z), vertical_accel(t) via pitch,roll,yaw
* ROT(t) - rate of turn

=== Assumptions

* No tacks, jibes during sample
* Heading and course over ground are mostly steady
* Wind is not changing drastically
* Depth is deep, i.e. depth > 1/2 wavelength
* Water current is not changing much (or zero i.e. negligible relative to boat speed)
* Trochoidal wave model
* Wave length is longer than boat length
* Approx formula for b, H (in trochoidal wave model)
* Accelerometer installed near vessel's center of mass (center of buoyancy)
* Vessel's geometry and RAO (Response amplitude operator) is not taken into account


=== Algorithm steps

Calculation steps:

* FFT to get observed wave frequency from acceleration (f_observed)
* Speed toward wave fronts (delta_v for Doppler frequency) from wind and speed data
+
**  COGT as true bearing from POS1 to POS2
**  Convert HDM to HDT using position and local mag declination, Use avg(HDT) vs COG and coordinates to calculate SPD
**  SPD = (DIST(POS1, POS2)/(t_end - t_start) - (DFT * cos(COGT - SET))) * cos(COGT - avg(HDT))
**  avg(leeway(heel(t), SPD))
**  use avg(AWA), AVG(AWS) and SPD to calculate TWS/TWA
**  TWS = sqrt(AVG(AWS) ^ 2 + SPD ^ 2 - 2 * AVG(AWS) * SPD * cos(avg(AWA)))
**  TWA = +- arccos( ( AVG(AWS) * cos(avg(AWA)) - SPD ) / TWS)
**  calculate delta_v as SPD * cos(TWA)
+
* Calculate L_source (source wave length) for trochoidal wave model from f_observed and delta_v using Doppler formulas
* Low pass filter for accel data
* min/max accel after low pass
* Calculate b value for trochoidal wave model from known L_source and min/max accel after low pass
* Calculate wave height from b and L_source


=== Input validation

* Validate heading and COG for steadiness
* Validate that magnetic variation is known for the position
* Check validity of accel (against g)
* Validate input data against assumptions
* Discard the sample if it is not good and start collecting a new one.


=== Result validation

* Validate wave amplitude max {nbsp} stem:[H < H_max = L / (2 pi)]
* Validate accel (Ratio to stem:[g] can't be unreasonably high)
* Discard the sample if the result is not good and start collecting a new one.
* Validate height calculated by Kalman filter against height calculated from max acceleration
and wavelength with trochoidal model.

== Further ideas

Trochoidal model gives a good reference point. It's easy to go from acceleration to vertical displacement
in trochoidal model knowing the wavelength. So (I think) it could be a good idea to use trochoidal model estimations
as input to Kalman filter fusion (instead of zero third integral assumption), as another way to prevent
displacement integral of acceleration from drift.

Vertical velocity and heel are correlated. It would be interesting to study their interdependencies.


== References

. Sharkh S. M., Hendijanizadeh2 M., Moshrefi-Torbati3 M., Abusara M. A.: A Novel Kalman Filter Based Technique for Calculating the Time History of Vertical Displacement of a Boat from Measured Acceleration, https://www.researchgate.net/profile/Mehdi-Hendijanizadeh/publication/264713649_A_Novel_Kalman_Filter_Based_Technique_for_Calculating_the_Time_History_of_Vertical_Displacement_of_a_Boat_from_Measured_Acceleration/links/53ec88db0cf24f241f1584c5/A-Novel-Kalman-Filter-Based-Technique-for-Calculating-the-Time-History-of-Vertical-Displacement-of-a-Boat-from-Measured-Acceleration.pdf[Marine Engineering Frontiers (MEF) Volume 2, 2014]
. https://en.wikipedia.org/wiki/Trochoidal_wave[Trochoidal Wave Wikipedia]
. Alexey A. Bobtsov, Nikolay A. Nikolaev, Olga V. Slita, Alexander S. Borgul, Stanislav V. Aranovskiy: The New Algorithm of Sinusoidal Signal Frequency Estimation. 11th IFAC International Workshop on
Adaptation and Learning in Control and Signal Processing
July 3-5, 2013. Caen, France: https://www.sciencedirect.com/science/article/pii/S1474667016329421[The New Algorithm of Sinusoidal Signal Frequency Estimation]
. https://en.wikipedia.org/wiki/Wind_wave[Wind Wave Wikipedia]
. https://wikiwaves.org/[Wiki Waves]
. https://github.com/seandepagnier/RTIMULib2[RTIMULib2 IMU library]
. https://github.com/pypilot/pypilot[PyPilot Free Autopilot]
. https://github.com/space-physics/wmm2020[World Magnetic Model on GitHub]


endif::[]
