= Bareboat Necessities Documentation
mgrouch <mgrouch@users.noreply.github.com>
1.0, Nov 18, 2019, Bareboat Projects Documentation
:toc:
:sectnums:
:icons: font
:encoding: utf-8
:lang: en
:title-logo-image: image:../../bareboat-necessities-logo.svg[]
:imagesdir: images

https://github.com/bareboat-necessities/my-bareboat

Bareboat Projects Documentation By

image::../../bareboat-necessities-logo.svg[]

== Boat Electronics Project

=== Raspberry Pi 4

image::RaspberryPi_4_Model_B.svg[alt=Raspberry Pi 4 Diagram]

This file is licensed under the Creative Commons Attribution-Share Alike 4.0 International license

https://creativecommons.org/licenses/by-sa/4.0/deed.en

=== Boat Computer

image::boat-computer.svg[alt=Boat Computer Diagram]

Raspberry Pi 4 has also WiFi and BlueTooth interfaces:

* 802.11ac/n
* Bluetooth 5.0

WiFi can be used to set up access to the boat computer from smart phones and tablets
with additional software.

==== Enclosure

. Case

 Brand: SZOMK,  Model: AK-D-09, IP54 protection, plastic box for PCB design instrument.
 Dimentions exterior: W 230mm, D 210mm, H 86mm

 Brand (from inside markings): BAHAR

 Model: BDH 20014-A2

 Cost: $17.10, Delivery: $13, Source: Alibaba

. Plastic sheets

 ABS Black Plastic Sheets Size 12" x 12", 0.118"-1/8" thick, 2-Pack, 1 Side Textured, Black

 Cost: $19.20, Source: Ebay

. USB 2.0 / HDMI

 USB 2.0 HDMI Mount Cable – USB Extension Flush, Dash, Panel Mount Cable,
 for Car, Boat, Motorcycle and More (3.3FT/1m)

 Cost: $10, Source: Amazon

. USB 3.0 / AUX

 USB 3.0 & Car Mount Flush Cable + USB3.0 AUX Extension Dash Panel Waterproof Mount Cable
 For Car Boat and Motorcycle - 3ft

 Cost: $10, Source: Amazon

. RJ45

 CAT6 RJ45 Shielded Industrial Panel Mount Bulkhead Female/Female Feed Thru Coupler -
 Network Connectors - IP67 Waterproof/Dust Cap (Single Pack, Black)

 Cost: $11.50, Source: Amazon

. Panel, etc

 Dual USB Socket Charger 2.1A&2.1A + LED Voltmeter + 12V Power Outlet + 5 Gang ON-Off Toggle Switch
 Multi-Functions Panel for Car Boat Marine RV Truck Camper Vehicles GPS Mobiles

 Cost: $34, Source: Amazon

 Used for panel parts: Voltmeter, Switches, Fuses, 12v DC Wires

. Fiber optic light pipes with lenses for panel mount for transfer of inside LED indicators light
to the front panel

 SMFLP12.0 492-1291-ND LIGHT PIPE CLEAR FLEXIBLE 12" (10 pack)

 Brand: Bivar Inc

 Cost: $28, Delivery: $9, Source: DigiKey

. 12v to 5v step-down converter

 TOBSUN EA50-5V DC 12V 24V to DC 5V 10A 50W Converter Regulator 5V 50W Power Supply Step Down Module Transformer

 Cost: $9.60, Source: Amazon

*    Convert unstable 12/24V DC power supply into stable 5V 10A DC power output
*    Over-voltage, over-current, over-temperature, short-circuit auto protection, and can return to normal conditions in the work
*    Essential for car audio system or other 5V car products (particularly useful in vehicles with 24V power supply)
*    Input voltage: 12/24V ,Output: 5V/10A
*    Widely used in automotive, surveillance systems, railway signals, medical equipment, instruments and meters, LED products, LED strips, cable TV and other low power test systems

===== Activities
. Make sure you use correct tools for:

* Measuring
* Cutting
* Clamping
* Drilling
* Heat Shrinking
* Tying
* Crimping
* Screwing

. Tools

 Drill, Screwdriver, Drill bits, Large hole drill bit, Cutting knife, Caliper


==== Computer Parts

. Raspberry Pi 4, 4Gb

. Heat sinks and Cooling fan

. Pi Case for mounting cooling fan

. USB Hub

. FTDI Serial to USB (2)

. SSD Drive

. SD Card

. 12v to 5v

. GPS mouse

. dAISy AIS

. RTL-SDR

. IMU + environmental sensors

. Make sure you use correct tools for the following activities

* Screwing
* Gluing
* Soldering

=== Cockpit Display and Chartplotter

image::cockpit-display.svg[alt=Cockpit Display Diagram]
