name: Publish Docs

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Publish AsciiDocs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: asciidoctor/docker-asciidoctor:1.17.1
          options: -v ${{ github.workspace }}:/documents/
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          run: |
            echo "Publishing AsciiDocs"
            mkdir -p output
            asciidoctor -b html5 -d book -a icons=font -a toc=left -D /documents/output docs/*.adoc
            asciidoctor-pdf -D /documents/output docs/*.adoc
            cd output ; cp -R ../docs/images images; cp -R ../docs/cockpit-ui cockpit-ui; cp -R ../docs/cards cards
            ls -ltr .
            echo "Done with AsciiDocs"
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/output