name: Publish Docs

on: [push]

jobs:
  build:
    name: Publish AsciiDocs
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: asciidoctor/docker-asciidoctor:1.17.1
          options: -v ${{ github.workspace }}:/documents/
          run: |
            echo "Publishing AsciiDocs"
            mkdir -p output
            asciidoctor -b html5 -d book -a icons=font -a toc=left -D /documents/output docs/*.adoc
            echo "Done with AsciiDocs"
